#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by scripts/render-installer-logo.sh from assets/images/helix-icon-256.png.
# Do not edit; re-run the script.

_LOGO_PX="193 159"

_logo_art() {
    case "$1" in
        256) cat <<'HELIX_LOGO_EOF'
   [38;5;24m▄[0m[38;5;31;48;5;31m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32m▄[0m[38;5;32m▄[0m[38;5;32m▄[0m             
  [38;5;24;48;5;24m▀[0m[38;5;24;48;5;25m▀[0m[38;5;31;48;5;31m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;74m▀[0m[38;5;109m▄[0m[38;5;180m▄[0m[38;5;209m▄[0m        
 [38;5;31m▄[0m[38;5;24;48;5;25m▀[0m[38;5;31;48;5;31m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;74m▀[0m[38;5;73;48;5;109m▀[0m[38;5;144;48;5;180m▀[0m[38;5;173;48;5;209m▀[0m[38;5;209;48;5;209m▀[0m[38;5;203;48;5;203m▀[0m[38;5;202;48;5;202m▀[0m[38;5;196m▄[0m     
[38;5;32m▄[0m[38;5;32;48;5;32m▀[0m[38;5;31;48;5;32m▀[0m[38;5;31m▀[0m[38;5;32m▀[0m[38;5;32m▀[0m[38;5;32m▀[0m[38;5;32m▀[0m[38;5;32m▀[0m[38;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;74;48;5;74m▀[0m[38;5;109;48;5;145m▀[0m[38;5;180;48;5;179m▀[0m[38;5;209;48;5;209m▀[0m[38;5;209;48;5;209m▀[0m[38;5;202;48;5;202m▀[0m[38;5;202;48;5;202m▀[0m[38;5;196;48;5;202m▀[0m[38;5;196;48;5;196m▀[0m[38;5;196;48;5;196m▀[0m[38;5;196m▄[0m  
[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32m▄[0m        [38;5;73m▀[0m[38;5;144m▀[0m[38;5;179;48;5;215m▀[0m[38;5;209;48;5;209m▀[0m[38;5;208;48;5;208m▀[0m[38;5;202;48;5;202m▀[0m[38;5;202;48;5;202m▀[0m[38;5;202;48;5;202m▀[0m[38;5;202;48;5;202m▀[0m[38;5;196;48;5;202m▀[0m[38;5;196;48;5;202m▀[0m[38;5;196;48;5;202m▀[0m 
[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32m▄[0m[38;5;32m▄[0m         [38;5;208m▀[0m[38;5;202m▀[0m[38;5;202;48;5;202m▀[0m[38;5;202;48;5;202m▀[0m[38;5;202;48;5;202m▀[0m[38;5;202;48;5;202m▀[0m[38;5;202;48;5;202m▀[0m[38;5;202;48;5;202m▀[0m[38;5;202;48;5;202m▀[0m
[38;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;38;48;5;74m▀[0m[38;5;74;48;5;109m▀[0m[38;5;144m▄[0m         [38;5;202m▀[0m[38;5;202;48;5;202m▀[0m[38;5;202;48;5;202m▀[0m[38;5;202;48;5;202m▀[0m[38;5;202;48;5;202m▀[0m[38;5;202;48;5;202m▀[0m
  [38;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;32m▀[0m[38;5;32;48;5;74m▀[0m[38;5;74;48;5;73m▀[0m[38;5;109;48;5;144m▀[0m[38;5;174;48;5;173m▀[0m[38;5;209;48;5;203m▀[0m[38;5;203;48;5;203m▀[0m[38;5;197m▄[0m[38;5;197m▄[0m[38;5;197m▄[0m[38;5;197m▄[0m[38;5;197m▄[0m[38;5;161m▄[0m[38;5;161m▄[0m[38;5;161m▄[0m[38;5;161m▄[0m[38;5;202;48;5;166m▀[0m[38;5;202;48;5;166m▀[0m[38;5;202;48;5;166m▀[0m[38;5;202m▀[0m
    [38;5;32m▀[0m[38;5;32m▀[0m[38;5;32;48;5;68m▀[0m[38;5;74;48;5;73m▀[0m[38;5;109;48;5;145m▀[0m[38;5;180;48;5;180m▀[0m[38;5;209;48;5;209m▀[0m[38;5;203;48;5;203m▀[0m[38;5;203;48;5;197m▀[0m[38;5;197;48;5;197m▀[0m[38;5;197;48;5;197m▀[0m[38;5;197;48;5;197m▀[0m[38;5;197;48;5;197m▀[0m[38;5;161;48;5;161m▀[0m[38;5;161;48;5;161m▀[0m[38;5;161;48;5;161m▀[0m[38;5;161;48;5;161m▀[0m[38;5;161;48;5;161m▀[0m[38;5;160;48;5;124m▀[0m[38;5;166;48;5;124m▀[0m[38;5;166;48;5;166m▀[0m 
        [38;5;180m▀[0m[38;5;173m▀[0m[38;5;203;48;5;203m▀[0m[38;5;203;48;5;203m▀[0m[38;5;197;48;5;197m▀[0m[38;5;197;48;5;196m▀[0m[38;5;196;48;5;196m▀[0m[38;5;197;48;5;197m▀[0m[38;5;197;48;5;161m▀[0m[38;5;161;48;5;161m▀[0m[38;5;161;48;5;161m▀[0m[38;5;161;48;5;161m▀[0m[38;5;161;48;5;161m▀[0m[38;5;161;48;5;125m▀[0m[38;5;124;48;5;124m▀[0m[38;5;124;48;5;88m▀[0m  
             [38;5;196m▀[0m[38;5;197m▀[0m[38;5;197;48;5;161m▀[0m[38;5;161;48;5;161m▀[0m[38;5;161;48;5;161m▀[0m[38;5;161;48;5;161m▀[0m[38;5;161;48;5;161m▀[0m[38;5;161;48;5;161m▀[0m[38;5;124;48;5;124m▀[0m[38;5;124m▀[0m   
HELIX_LOGO_EOF
            ;;
        16) cat <<'HELIX_LOGO_EOF'
   [36m▄[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36m▄[0m[36m▄[0m[36m▄[0m             
  [90;100m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[90m▄[0m[90m▄[0m[33m▄[0m        
 [36m▄[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[90;100m▀[0m[90;100m▀[0m[90;43m▀[0m[33;43m▀[0m[91;101m▀[0m[91;101m▀[0m[91m▄[0m     
[36m▄[0m[36;46m▀[0m[36;46m▀[0m[36m▀[0m[36m▀[0m[36m▀[0m[36m▀[0m[36m▀[0m[36m▀[0m[36m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;100m▀[0m[90;100m▀[0m[90;100m▀[0m[33;43m▀[0m[33;43m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91m▄[0m  
[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36m▄[0m        [90m▀[0m[90m▀[0m[90;43m▀[0m[33;43m▀[0m[33;43m▀[0m[91;43m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m 
[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36m▄[0m[36m▄[0m         [33m▀[0m[33m▀[0m[91;43m▀[0m[91;43m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m
[36m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[94;100m▀[0m[90m▄[0m         [33m▀[0m[33;43m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m
  [36m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[36;46m▀[0m[94;100m▀[0m[90;100m▀[0m[90;100m▀[0m[90;101m▀[0m[91;101m▀[0m[91m▄[0m[91m▄[0m[91m▄[0m[91m▄[0m[91m▄[0m[91m▄[0m[91m▄[0m[31m▄[0m[31m▄[0m[91;41m▀[0m[91;41m▀[0m[91;101m▀[0m[91m▀[0m
    [36m▀[0m[36m▀[0m[36;46m▀[0m[94;100m▀[0m[90;100m▀[0m[90;100m▀[0m[90;100m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;41m▀[0m[31;41m▀[0m[31;41m▀[0m[31;41m▀[0m[31;41m▀[0m[31;41m▀[0m 
        [90m▀[0m[90m▀[0m[33;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[91;101m▀[0m[31;41m▀[0m[31;41m▀[0m[31;41m▀[0m[31;41m▀[0m[31;41m▀[0m[31;41m▀[0m  
             [91m▀[0m[91m▀[0m[91;101m▀[0m[91;101m▀[0m[31;41m▀[0m[31;41m▀[0m[31;41m▀[0m[31;41m▀[0m[31;41m▀[0m[31m▀[0m   
HELIX_LOGO_EOF
            ;;
        kitty) cat <<'HELIX_LOGO_EOF'
_Ga=T,f=100,r=10,C=1,q=2,m=1;iVBORw0KGgoAAAANSUhEUgAAAMEAAACfCAMAAAB3GE0pAA
AAwFBMVEUAAAADk9vmFzD1Yykcm9wMlt0Rl90HaaDuHi7uIjGjCyrtKjb3ZTT5YivylmH4Yy/wYE
1Wp9HZrZClqq7znGPym2MHSHXVrY31mV2jqal0ByClqajXroxWoMhXochUn8j3aUkHO2P5bkj8hz
LvOUP5hTn7hjXi6NuVsMn7hjTu1aJxobufqKr5akee2edxoboFgL7Wq4wcbJxyobqrGitwoblvze
mcCyMOSHEUa5+bDiMMZZzNtM4qgrXnyXcWUXe8rZQyAAAAQHRSTlMA9Pb1H6Bf/aFg/SMhohRdEA
8SFKJe/abIov1eXZtdymH7pdkRGVoBCKQBn8XLAST+wxphGMYCnJ9RWpkBCwEjlgeV/QAAEOdJRE
FUeNrVnGlD3DgSht3dtvvybQghhCPh6KZJYBKSTI6dmf//r1ZSSaWSLF9gk44/DA27s6tHqrfeKk
luz+v6+L4fyod9zL0/6/nncxgEE/oEAQf5Qzj8zz/m84nzERj7Pv7PP37N53UEEmOfKf6B8c//mj
Q/e0vxGcbfTgDK2DuK/Md8XkcQsAEHlrr3bik+f3+FBHWzHrIMa3Lwpcj3D2DerABuFYH5t3zPAP
5q1/E9N7xgjyAMgHlVBC6K3Mspxe+F+O/7q5YlCMKKkkHH9ySk2F/uf9MKeK9edVBBIKqkoCqBb5
qC/eG3IBgA81Yb8CmGTKk5UvwGiP/evXrVXceOfKR8QUO8rE8wFbcsQVBjZnQx1MxLCvZr+XII79
qDKAgqEpAzTyjYH3bC3BHihZaAA3QKIlFcGxgBjFJ7A/t9y/9H7yVE/vAC1dD3d911rDRgmZlvaE
BNPfvLZHJ6NjrDj3fNOnbYGR/zhmLYSkaIPDw9P398GFUR/ncriCZuIdscYpC+4QM+0QDLRmDQRX
529/X4pHy5JZg3+EDVzXyqASsdBWG+Eb+WD3cfxmP49utddzMQSna5Gf4RGwZYitMzuRDlyfGnt8
UoEP68PYjalFzjZgyCiKB8e/T64LAYniB81RZEbg349w2ejFXqjoqgSA4YQzL0EnidgigIqm4WVt
zMN91sC3PPAuj4pIDJTw4HZwjnfezMWZdqChSBVLIUgVeeHH06eqsZLrIBCYJ5fzurUbIJseV/OT
+VIigKpoLDRPQO2cXHj8Mx+JN5SxC57czok2HQG+JmMPdlfnbKRSAhDpkKkgIYZnE6EEM4sYTstr
PQ0ZxtHHVprpW8QRGgFSSHqOQsZgzRIEE06WxnThGYbpYbSlYiKI8/HEkr0NkoieLZdACGShC1iC
A0fEAGvdGb3RMln+YSgongk7QCwpDG08UyenYQ9SHQUjYLU5h4u6RjIji/e1QiYCpQaTQ5nM2ECr
J0yhiyZwYRJ2jtzoJmKcv4qdSl5cMjqekSouSYMfDZj5aMYb17RmcwsQjq7azanX3zHLss8k+4cS
Ts7C3aGWdITIYFZ3iGDCyCVg0E9S2mVZcqN+N2dqTsjNQVkWTIloxhuX6yDEyCvzrVdEFQZ2e0Lj
0/P31UpShTMtYSjOE2lUoGVxCh9DQ5+IEg6KFjGHRuiUA4MBqBj0LWbkbtbJPwkXOGKJ1NF5xh/d
RQYkHUTlBVchComs60M7suFRo4lvFDAyhBP4tiNvQIlmH6hGUIOUHnzUZXd2Y3Z1U3O+EaqIggww
hK+dAZA0fovQx5YBG0ho/TzkKzr0Ehazc7OkIRHL6+vIF1SGezOEr09PNI6qtoX/wfdyXQO6ZhrZ
JVcyZ6s9MTLeSDAykCsDO5DpxBJ9Ss/zKE7QQuEfhGQqprzh5Yc6a7+0LXdF6irEAk1FgkVJh+WI
asXxDxMOpgZ6HTzqyWoKpkUdJVRJAoK+ChNBXlnUxGAqH7MkAQEYKWLYqw2thUdyhwm8VT3T02Z1
wEryVDipYcQ0IFNURC0NNlryBiYdSxO6up6Ug1RLdZznLdnDEhbyTD5eWtFgFPRolQgbUM3QSdq6
H0tDOvamdVCFGXOkVwc6lEgEJOaTKKukeSP+lPgPmmyc6wLmV2Vla3WZIbW8gqGSWQjDrnpHBiIe
ANHPKAkwWuU0xCEfg1dnZ87BAB1nRiGUSnEC3IMqw7iiEPLIJfP+quQeWA4vDkak0ni+tcK5kx7J
ABamtDyEIOcvpVPgWEfzsGkUD49ePzpj3u7H2WkO6Y0nTE7OysJG6Gzdnt5e1NgrMfCUVrIbN5Bx
VkXfQc0gn9p8dGsV1ebx1OwIWs9xqLQ0MEopYAIdPKSIZ/AT/a9Zwbsd33tMs6+3ApOX/kuyyFbj
Dldpeoh6C2toTsrWUk8RBqR/Ct/PKEDrVSmG4khJ+T5sxoMAudRhMSSsrOpApkWm1BCM3sEj7tPo
RvF6aeKkw3FUtmDJe3usGMox18EAwpEfIikiSNCLmdIMOn99qVdOTz/VJ1/MeUrCZfC3mDNR1fBv
4B8un6X0MFTQh+xaiec/CrAooo+e7r12O6XyrroevbWSwYMowg+UH5GKggakUIHVb7zN0/S8kPfL
+0ukNhW0Hi7dKYLANaQguCFUTBEAgaQrfJuMuy1ScfmIwSHLpcBunMMqCaEewgGghBFRa4VyQ6TH
16IxvM60oy4j+Zre2MwgiMGRyuPYjCoRDkyQcrrnfSzo60Jd9eSgYQcqE9gf/krQ6MHWoMsRaAsE
zaMhEL3+EQ+EqwNvnuUe+XSoaNYLiWoWREEFc2ry4iXRipVXCVeb6r8h8SAbLRnbnnK5PR5UwwoB
XAB9g6mqY7yELRElXgRAgn4yOwbMTrisqeb3ITw2bFDiIowcTKG85pHMHgKwiGmovA1bmEgyN4/B
zfsGRZW/MRX8sIinEZkh3UqfcwYiJkWJbGIBLF5ggITMhGg3l5e63r0kSHkmKJZjySEjdC0SwDSO
TB8woM5wN1qWa4oXWp9gTOEkFOivnZDhu8CCTBIYIpbZEBRfCHZniNpRHrDwRDYlcVsuOUHU9kIY
gnIkdPLhkAwgiRZB7esMrIjCC1HjuIpA2k1UiHECLEWX0QEQQ/GAMBhHyDTTK3s2pVAXmV/zajCA
uFkDYTGAiTcAQGJYJr286Uv8lliThCmlYR4qiZAJIRq8vGiSQlZG5n10YEsZiCsWfiB7OEGBFiFP
J0KoyvTshQ24EKwm8jRRIbuZmM+NDV9GsV8BASJBphBgA8W9USTGTsyGZrpEjiQpbrYNlZBOEvVZ
AShJn6B/zn9QQTeQ4spz8caxkSkYxuXHZGVQAIsRi4/McMFyGcNCKE0HOOtwxmXSo+wPRSFcQSQQ
x7BqPHRfBrY4hYQjjiMpBkFNM8GiVUBQYCPsIT/EkLgookZBn+UUNXLGpdDBWIEVsEIoz8BiVDCO
HQ/ZGXQeVRHHtCEGZOhFie5LtkoBHCe70MwajLoASsfwpNQAhVF0CFUVBzPqOTUehvcRlGC6VrmO
9rOf3XcuKJCpwIkTsZ6coUkpFSQSAO7sWHzejLQEMohrVwIKQNySjwaTK693wVQaPJQY1ZTj/8Gh
Mhu8KoTgghqYyMZBSIqwdjyUFO+L0cewcEIYT6Tp8mo0DNfqgYxnitRqqhkAqO2hGc+TTQCDBmK4
L4h61gGP61RRk6ppDTuEYFkqCy4yUPwmgykstwT2YfPvm7cSJJIsgs1IDgLo2CumQEd6HU7N/zvw
0vaYeQ3XZGSqOgpkELdHEtLRnuc4UYQcCQj5KTQBMQQvUIdRU2KesCXy9DIOdcf/Jy9hFv8w710F
wEITSr87TUqy6CbtACHLtYhlKHEjDIu2j56fnQDLSoaFIBtpq+eXRAECDoLUu2GTb56enpw8MIYp
AItSpQnSaJIycC37gzEqq6xBLguWd+dndXliMYdIuQkQDjKNBm4PuyxYSh38vlUMkIbohrhrI8OR
mSoeiWi6LK7qmBEGCLaUQQSUZMyZNzfMGGP4PrOW6IoVmcVLdPKwghGbqIoG9GMhLXJk7lyMdASJ
sQyAYw1G/WNoWvxq6WIVcf1CdRZW8ZwyivKUYEoVnIGEcVBI8mo9BIRmBnEEDbXLxlNhZCNwJACC
0EWdXJoYsLW4SBb0me4s2P\_Gm=0;YzwwfjGEuHqgFoTWZpGtAl9NvmTgIsi36qz1E94ofRmE1
DpxDPGFM3m7zFIBtTO8Qee6yHg/eIURdwgiVHOoa2tPWkKu/NfJUG5PyI3k5OD1sC9bNiCk1fsJ+
gwwNHsbLKR1NcqxgrOtEgG+Luolh+8/fnw/3JuKHezMhQBVXZhvVObXKhAfvqmaDhn0+zXe/5ILB
hEPBVGHELteX6sgqESa61JOm4JXcoYT8rqoupbvZdmFOPZaD0CR1Xha6r5UE1Rqa0PJYva/kXpoe
3b8wbr+pCDk2d3zIaJ41jGITAQsjIgKcPb5n2Q9BK+L4tUh+ub3WkBwivXwCHFdupDindCqQvwRI
0jZ2fm5EgG9kVxwJTMhw6+ZhBAU2fNsoVMQEQToy4wI4oFDGZgVnJWQ/PlFRhQBF/KMCTkzIRgFw
0ieruZOQWQj5ErIOpREGlV2dqdFUOgbyd4mu4jFvF8Z4SQw+Gr040j4v95SUVgIIVpy4Jt5NLQY+
Msp9HVRDZFFppIJhFqOq3V7CcJo5b/YOYiwwAgbClMeS/ICHTAUW7xxwDSgIOBKCp90sTN2ZVLw9
WAkHCWrSCTJ+NiX+gx/1cEMaI8Xkr2iSlGXo53lFTsTbmZAYDpKXBCIImDkI361/iuraY8l8DBxq
lnHykjLQdjZnbazTwf4gk3GhZxGmVdNR1ciMJYLF0bzs1p11bGJQOxMuRjZbKQioC/YeCDkxfIqs
dIRCGDH/7Jc9CRYdTGDqp5NFQR2d1aS5gxu88r42aAlr5UkjXzE7eGqD4ZJkHbLYlZ/QBhEZ7PVz
ZmuSw+4CDZ05heYVDMrH4GMl8suQbVaGQhdv5NAjj3XbQEWRJxBWkHJmzP1PThMBLMZlqWGBiC1V
6WsRNzIYRLEnb1ERpLOQRtf29kj1nQlfPmBKunSeDaN0+zfiiVDYZHUB089xMpASLvb4a7SJQsrg
NaYWQG9gEmELG68oplt9JBBADKtLvoJmRD0+mILY69I2Rlr78Xk7wr9XkfBLwG+RyOwhHxlCZlpI
1l3z6sA8GbVN4g8dURAklEu9oeYFah66O0ReVOON5jKYImZ7SrpSMY/Ly26YKxWdBF6f7eI2SULE
WzJ14mJd1OkkpPs4j1/MSuTv2kh63S0sGMfjbiV4A0swXX/4hZzUO60AuMbrfhXB8ymSgPZFZXAl
aRwK7krQfqU+jwPnd0ZDSC8RcqzkRSBHT1QWjfno6YgeuM9KYh0KKEVfH3UIjDeMlMlXWIpOas48
jrLrnoKefVGSDl+8m6UtrPy8e4D1nT6a91UXSrjJ0NLzjxXcS09ed3Bkw2C1Hv6o+2Mt/dYDx3qH
QpZl1oNppj0WgnIynrRZmeK4Fl7H2BnpRTBp6OidNjZBX/dHpWMdYWy5PV6uehdWROC5ywBdAX8A
LnAesh8y0wW06jkxIoeUIDXt7hGAE7w/C/L2nE7w9cUj3RNB3Wp2mVRbna1sW1A1tbdKVaUIB5iL
7N8uPuqLVl/BUjB7OwjE0FC6gpdHq2rtfW6W21tEKTeIE9Rkr3GhOxQJEwEs4WtZBE9mbtNBh03G
fLKIBhsT5wp+UOdnUGHaRvBQppD7zaZALyZxkN+D2Rp1HQHeociMTd9DTeD6rpXPqIEQwURBpMQM
tlrRAhlZ2zARUUEPaxsxCBSDIVd02klk+o6c5WlnYpSiyD1hn/KpNJhOuxM1qWZSwOLhWuHyy2Dy
BvlMSwZRFCFQA08zc2AIPXGegozG62XcsBJZZNF2ll3KRtBFHkjPvamr7FdWkk+aquos5sJgqU37
mMW1569XeqKnrai9CWXQB1h8uIaD//WVMnrOiV3XYLV0nuRR2z6Tl1tDSp53Wu3FJfg78h7oQdPb
xyerFrlq3X33VK1BF+8F3xoc5Y5NbDAw46uBD+9F35MDexqerNmN1sRgp+J9/KP7WZ961ICsPr7i
/d7HtPNxG5pdyXvA0DNucd63dPNfiuAA4IWpsv2km4PAPBcflp3ELtoJPi5DwBef0PWADtvj54ef
rxPEWTHUycKNf7M28unQ0YV4//5xdvjZ9dob2L4a2//n5rDwAUb/hfvz3ngIo6807KUm8Mdn/8D9
TqzQXQBq+oAAAAASUVORK5CYII=\
HELIX_LOGO_EOF
            ;;
        iterm) cat <<'HELIX_LOGO_EOF'
]1337;File=inline=1;height=10;preserveAspectRatio=1:iVBORw0KGgoAAAANSUhEUgA
AAMEAAACfCAMAAAB3GE0pAAAAwFBMVEUAAAADk9vmFzD1Yykcm9wMlt0Rl90HaaDuHi7uIjGjCyr
tKjb3ZTT5YivylmH4Yy/wYE1Wp9HZrZClqq7znGPym2MHSHXVrY31mV2jqal0ByClqajXroxWoMh
XochUn8j3aUkHO2P5bkj8hzLvOUP5hTn7hjXi6NuVsMn7hjTu1aJxobufqKr5akee2edxoboFgL7
Wq4wcbJxyobqrGitwoblvzemcCyMOSHEUa5+bDiMMZZzNtM4qgrXnyXcWUXe8rZQyAAAAQHRSTlM
A9Pb1H6Bf/aFg/SMhohRdEA8SFKJe/abIov1eXZtdymH7pdkRGVoBCKQBn8XLAST+wxphGMYCnJ9
RWpkBCwEjlgeV/QAAEOdJREFUeNrVnGlD3DgSht3dtvvybQghhCPh6KZJYBKSTI6dmf//r1ZSSaW
SLF9gk44/DA27s6tHqrfeKkluz+v6+L4fyod9zL0/6/nncxgEE/oEAQf5Qzj8zz/m84nzERj7Pv7
PP37N53UEEmOfKf6B8c//mjQ/e0vxGcbfTgDK2DuK/Md8XkcQsAEHlrr3bik+f3+FBHWzHrIMa3L
wpcj3D2DerABuFYH5t3zPAP5q1/E9N7xgjyAMgHlVBC6K3Mspxe+F+O/7q5YlCMKKkkHH9ySk2F/
uf9MKeK9edVBBIKqkoCqBb5qC/eG3IBgA81Yb8CmGTKk5UvwGiP/evXrVXceOfKR8QUO8rE8wFbc
sQVBjZnQx1MxLCvZr+XII79qDKAgqEpAzTyjYH3bC3BHihZaAA3QKIlFcGxgBjFJ7A/t9y/9H7yV
E/vAC1dD3d911rDRgmZlvaEBNPfvLZHJ6NjrDj3fNOnbYGR/zhmLYSkaIPDw9P398GFUR/ncriCZ
uIdscYpC+4QM+0QDLRmDQRX529/X4pHy5JZg3+EDVzXyqASsdBWG+Eb+WD3cfxmP49utddzMQSna
5Gf4RGwZYitMzuRDlyfGnt8UoEP68PYjalFzjZgyCiKB8e/T64LAYniB81RZEbg349w2ejFXqjoq
gSA4YQzL0EnidgigIqm4WVtzMN91sC3PPAuj4pIDJTw4HZwjnfezMWZdqChSBVLIUgVeeHH06eqs
ZLrIBCYJ5fzurUbIJseV/OT+VIigKpoLDRPQO2cXHj8Mx+JN5SxC57czok2HQG+JmMPdlfnbKRSA
hDpkKkgIYZnE6EEM4sYTstrPQ0ZxtHHVprpW8QRGgFSSHqOQsZgzRIEE06WxnThGYbpYbSlYiKI8
/HEkr0NkoieLZdACGShC1iCA0fEAGvdGb3RMln+YSgongk7QCwpDG08UyenYQ9SHQUjYLU5h4u6R
jIji/e1QiYCpQaTQ5nM2ECrJ0yhiyZwYRJ2jtzoJmKcv4qdSl5cMjqekSouSYMfDZj5aMYb17Rmc
wsQjq7azanX3zHLss8k+4cSTs7C3aGWdITIYFZ3iGDCyCVg0E9S2mVZcqN+N2dqTsjNQVkWTIlox
huX6yDEyCvzrVdEFQZ2e0Lj0/P31UpShTMtYSjOE2lUoGVxCh9DQ5+IEg6KFjGHRuiUA4MBqBj0L
WbkbtbJPwkXOGKJ1NF5xh/dRQYkHUTlBVchComs60M7suFRo4lvFDAyhBP4tiNvQIlmH6hGUIOUH
nzUZXd2Y3Z1U3O+EaqIggwwhK+dAZA0fovQx5YBG0ho/TzkKzr0Ehazc7OkIRHL6+vIF1SGezOEr
09PNI6qtoX/wfdyXQO6ZhrZJVcyZ6s9MTLeSDAykCsDO5DpxBJ9Ss/zKE7QQuEfhGQqprzh5Yc6a
7+0LXdF6irEAk1FgkVJh+WIasXxDxMOpgZ6HTzqyWoKpkUdJVRJAoK+ChNBXlnUxGAqH7MkAQEYK
WLYqw2thUdyhwm8VT3T02Z1wEryVDipYcQ0IFNURC0NNlryBiYdSxO6up6Ug1RLdZznLdnDEhbyT
D5eWtFgFPRolQgbUM3QSdq6H0tDOvamdVCFGXOkVwc6lEgEJOaTKKukeSP+lPgPmmyc6wLmV2Vla
3WZIbW8gqGSWQjDrnpHBiIeANHPKAkwWuU0xCEfg1dnZ87BAB1nRiGUSnEC3IMqw7iiEPLIJfP+q
uQeWA4vDkak0ni+tcK5kx7JABamtDyEIOcvpVPgWEfzsGkUD49ePzpj3u7H2WkO6Y0nTE7OysJG6
Gzdnt5e1NgrMfCUVrIbN5BxVkXfQc0gn9p8dGsV1ebx1OwIWs9xqLQ0MEopYAIdPKSIZ/AT/a9Zw
bsd33tMs6+3ApOX/kuyyFbjDldpeoh6C2toTsrWUk8RBqR/Ct/PKEDrVSmG4khJ+T5sxoMAudRhM
SSsrOpApkWm1BCM3sEj7tPoRvF6aeKkw3FUtmDJe3usGMox18EAwpEfIikiSNCLmdIMOn99qVdOT
z/VJ1/MeUrCZfC3mDNR1fBv4B8un6X0MFTQh+xaiec/CrAooo+e7r12O6XyrroevbWSwYMowg+UH
5GKggakUIHVb7zN0/S8kPfL+0ukNhW0Hi7dKYLANaQguCFUTBEAgaQrfJuMuy1ScfmIwSHLpcBun
MMqCaEewgGghBFRa4VyQ6TH16IxvM60oy4j+Zre2MwgiMGRyuPYjCoRDkyQcrrnfSzo60Jd9eSgY
QcqE9gf/krQ6MHWoMsRaAsEzaMhEL3+EQ+EqwNvnuUe+XSoaNYLiWoWREEFc2ry4iXRipVXCVeb6
r8h8SAbLRnbnnK5PR5UwwoBXAB9g6mqY7yELRElXgRAgn4yOwbMTrisqeb3ITw2bFDiIowcTKG85
pHMHgKwiGmovA1bmEgyN4/BzfsGRZW/MRX8sIinEZkh3UqfcwYiJkWJbGIBLF5ggITMhGg3l5e63
r0kSHkmKJZjySEjdC0SwDSOTB8woM5wN1qWa4oXWp9gTOEkFOivnZDhu8CCTBIYIpbZEBRfCHZni
NpRHrDwRDYlcVsuOUHU9kIYgnIkdPLhkAwgiRZB7esMrIjCC1HjuIpA2k1UiHECLEWX0QEQQ/GAM
BhHyDTTK3s2pVAXmV/zajCAuFkDYTGAiTcAQGJYJr286Uv8lliThCmlYR4qiZAJIRq8vGiSQlZG5
n10YEsZiCsWfiB7OEGBFiFPJ0KoyvTshQ24EKwm8jRRIbuZmM+NDV9GsV8BASJBphBgA8W9USTGT
syGZrpEjiQpbrYNlZBOEvVZAShJn6B/zn9QQTeQ4spz8caxkSkYxuXHZGVQAIsRi4/McMFyGcNCK
E0HOOtwxmXSo+wPRSFcQSQQx7BqPHRfBrY4hYQjjiMpBkFNM8GiVUBQYCPsIT/EkLgookZBn+UUN
XLGpdDBWIEVsEIoz8BiVDCOHQ/ZGXQeVRHHtCEGZOhFie5LtkoBHCe70MwajLoASsfwpNQAhVF0C
FUVBzPqOTUehvcRlGC6VrmO9rOf3XcuKJCpwIkTsZ6coUkpFSQSAO7sWHzejLQEMohrVwIKQNySj
waTK693wVQaPJQY1ZTj/8GhMhu8KoTgghqYyMZBSIqwdjyUFO+L0cewcEIYT6Tp8mo0DNfqgYxni
tRqqhkAqO2hGc+TTQCDBmK4L4h61gGP61RRk6ppDTuEYFkqCy4yUPwmgykstwT2YfPvm7cSJJIsg
s1IDgLo2CumQEd6HU7N/zvw0vaYeQ3XZGSqOgpkELdHEtLRnuc4UYQcCQj5KTQBMQQvUIdRU2Kes
CXy9DIOdcf/Jy9hFv8w710FwEITSr87TUqy6CbtACHLtYhlKHEjDIu2j56fnQDLSoaFIBtpq+eXR
AECDoLUu2GTb56enpw8MIYpAItSpQnSaJIycC37gzEqq6xBLguWd+dndXliMYdIuQkQDjKNBm4Pu
yxYSh38vlUMkIbohrhrI8ORmSoeiWi6LK7qmBEGCLaUQQSUZMyZNzfMGGP4PrOW6IoVmcVLdPKwg
hGbqIoG9GMhLXJk7lyMdASJsQyAYw1G/WNoWvxq6WIVcf1CdRZW8ZwyivKUYEoVnIGEcVBI8mo9B
IRmBnEEDbXLxlNhZCNwJACC0EWdXJoYsLW4SBb0me4s2PYzwwfjGEuHqgFoTWZpGtAl9NvmTgIsi
36qz1E94ofRmE1DpxDPGFM3m7zFIBtTO8Qee6yHg/eIURdwgiVHOoa2tPWkKu/NfJUG5PyI3k5OD
1sC9bNiCk1fsJ+gwwNHsbLKR1NcqxgrOtEgG+Luolh+8/fnw/3JuKHezMhQBVXZhvVObXKhAfvqm
aDhn0+zXe/5ILBhEPBVGHELteX6sgqESa61JOm4JXcoYT8rqoupbvZdmFOPZaD0CR1Xha6r5UE1R
qa0PJYva/kXpoe3b8wbr+pCDk2d3zIaJ41jGITAQsjIgKcPb5n2Q9BK+L4tUh+ub3WkBwivXwCHF
dupDindCqQvwRI0jZ2fm5EgG9kVxwJTMhw6+ZhBAU2fNsoVMQEQToy4wI4oFDGZgVnJWQ/PlFRhQ
BF/KMCTkzIRgFw0ieruZOQWQj5ErIOpREGlV2dqdFUOgbyd4mu4jFvF8Z4SQw+Gr040j4v95SUVg
IIVpy4Jt5NLQY+Msp9HVRDZFFppIJhFqOq3V7CcJo5b/YOYiwwAgbClMeS/ICHTAUW7xxwDSgIOB
KCp90sTN2ZVLw9WAkHCWrSCTJ+NiX+gx/1cEMaI8Xkr2iSlGXo53lFTsTbmZAYDpKXBCIImDkI36
1/iuraY8l8DBxqlnHykjLQdjZnbazTwf4gk3GhZxGmVdNR1ciMJYLF0bzs1p11bGJQOxMuRjZbKQ
ioC/YeCDkxfIqsdIRCGDH/7Jc9CRYdTGDqp5NFQR2d1aS5gxu88r42aAlr5UkjXzE7eGqD4ZJkHb
LYlZ/QBhEZ7PVzZmuSw+4CDZ05heYVDMrH4GMl8suQbVaGQhdv5NAjj3XbQEWRJxBWkHJmzP1PTh
MBLMZlqWGBiC1V6WsRNzIYRLEnb1ERpLOQRtf29kj1nQlfPmBKunSeDaN0+zfiiVDYZHUB089xMp
ASLvb4a7SJQsrgNaYWQG9gEmELG68oplt9JBBADKtLvoJmRD0+mILY69I2Rlr78Xk7wr9XkfBLwG
+RyOwhHxlCZlpI1l3z6sA8GbVN4g8dURAklEu9oeYFah66O0ReVOON5jKYImZ7SrpSMY/Ly26YKx
WdBF6f7eI2SULEWzJ14mJd1OkkpPs4j1/MSuTv2kh63S0sGMfjbiV4A0swXX/4hZzUO60AuMbrfh
XB8ymSgPZFZXAlaRwK7krQfqU+jwPnd0ZDSC8RcqzkRSBHT1QWjfno6YgeuM9KYh0KKEVfH3UIjD
eMlMlXWIpOas48jrLrnoKefVGSDl+8m6UtrPy8e4D1nT6a91UXSrjJ0NLzjxXcS09ed3Bkw2C1Hv
6o+2Mt/dYDx3qHQpZl1oNppj0WgnIynrRZmeK4Fl7H2BnpRTBp6OidNjZBX/dHpWMdYWy5PV6ueh
dWROC5ywBdAX8ALnAesh8y0wW06jkxIoeUIDXt7hGAE7w/C/L2nE7w9cUj3RNB3Wp2mVRbna1sW1
A1tbdKVaUIB5iL7N8uPuqLVl/BUjB7OwjE0FC6gpdHq2rtfW6W21tEKTeIE9Rkr3GhOxQJEwEs4W
tZBE9mbtNBh03GfLKIBhsT5wp+UOdnUGHaRvBQppD7zaZALyZxkN+D2Rp1HQHeociMTd9DTeD6rp
XPqIEQwURBpMQMtlrRAhlZ2zARUUEPaxsxCBSDIVd02klk+o6c5WlnYpSiyD1hn/KpNJhOuxM1qW
ZSwOLhWuHyy2DyBvlMSwZRFCFQA08zc2AIPXGegozG62XcsBJZZNF2ll3KRtBFHkjPvamr7FdWkk
+aquos5sJgqU37mMW1569XeqKnrai9CWXQB1h8uIaD//WVMnrOiV3XYLV0nuRR2z6Tl1tDSp53Wu
3FJfg78h7oQdPbxyerFrlq3X33VK1BF+8F3xoc5Y5NbDAw46uBD+9F35MDexqerNmN1sRgp+J9/K
P7WZ961ICsPr7i/d7HtPNxG5pdyXvA0DNucd63dPNfiuAA4IWpsv2km4PAPBcflp3ELtoJPi5DwB
ef0PWADtvj54efrxPEWTHUycKNf7M28unQ0YV4//5xdvjZ9dob2L4a2//n5rDwAUb/hfvz3ngIo6
807KUm8Mdn/8D9TqzQXQBq+oAAAAASUVORK5CYII=
HELIX_LOGO_EOF
            ;;
        sixel) cat <<'HELIX_LOGO_EOF'
P0;1;0q"1;1;193;159#1;2;79;69;59#2;2;89;67;50#3;2;64;67;67#4;2;94;61;43#5;2
;97;60;32#6;2;81;63;54#7;2;54;64;70#8;2;29;66;84#9;2;25;63;83#10;2;28;62;80#
11;2;12;61;87#12;2;23;60;80#13;2;13;60;84#14;2;9;60;86#15;2;5;61;88#16;2;4;5
9;87#17;2;4;59;87#18;2;2;59;88#19;2;4;58;86#20;2;2;58;87#21;2;0;58;88#22;2;0
;58;87#23;2;2;58;86#24;2;0;58;87#25;2;0;58;87#26;2;0;58;87#27;2;0;57;85#28;2
;96;53;34#29;2;98;52;21#30;2;97;46;23#31;2;98;46;15#32;2;97;42;20#33;2;95;41
;16#34;2;98;42;14#35;2;96;38;21#36;2;97;38;14#37;2;97;31;19#38;2;96;25;19#39
;2;96;21;19#40;2;96;15;18#41;2;93;39;21#42;2;93;18;21#43;2;70;30;34#44;2;3;3
8;59#45;2;0;57;86#46;2;0;56;85#47;2;0;56;84#48;2;0;54;82#49;2;1;41;69#50;2;9
4;10;18#51;2;95;10;16#52;2;92;9;19#53;2;91;8;19#54;2;93;7;18#55;2;91;7;18#57
;2;89;9;19#58;2;89;7;19#59;2;87;6;19#60;2;79;5;19#61;2;59;3;15#19!52?___?A!4
?C!4?G!7?_$#20!55?_$#22!50?A!16?oO$#23!49?A???AA?__??C???GG???OO??_$#24!51?A
!18?___$#25!62?__$#26!63?O$#27!47?AE??_!4?W???GoO?ooo?__$#44!30?__ooW$#45!59
?c_GGG$#46!49?w{[][[]C[{WO$#47!43?_}}}{wC$#48!38?o{}}}]$#49!34?_ww{K-#16!56?
_$#18!59?_$#19!52?O?O!22?@???A??C??G??O??_$#20!51?O!9?``?C!6?OSC??@!8?__?O$#
21!70?O$#22!60?_!4?GG?O_???__@AAA!6?O?O$#23!53?P@`@@?@@??_??AAG!6?_?GG?AOOC?
?G_?O___$#24!51?G@!10?@___GAO___?!5CACKCWWGO?__$#25!52?G!8?C??G?@O_!4?AB!7?G
$#26!54?GMMK!4?WGOOO@@???A@?A$#27!49?Gw?EMC???KWWW?O???_?@?@@$#44!23?_ow{}}~
~~N@$#45!54?A??AQEE?CC@@???A@A!7?CG$#46!47?O}vFf___OOO!12?A!8?G$#47!40?_{!5~
n@$#48!37?w~~^B$#49!32?o}~~~F-#12!110?_$#13!106?_o__$#14!102?COWOO$#15!95?_$
#16!72?G!6?_??A$#17!79?@!9?G??O!6?A$#18!76?C?@??A!5?GG$#19!52?G?G!25?G???O!4
?__???_?CCA?G??G$#20!49?CCK!16?C??G???O?C_?ACC??CO???OO__$#21!58?_!27?G$#22!
50?G?C!17?OO??@BB`AAC??C?G?OOO!4?@AA$#23!53?G?GO???_O???A@`???A!6?C??GG?CO??
?@@_?BA@@ACCCKG$#24!54?OO?G@`@?AQA?_C@Hg__qq__??C???GG!7?@$#25!53?CC??@???M?
CCO??G???O@???A$#26!55?`FA?AE???G???OO$#27!46?_c}oa_BbBA??MC!5?GG$#44!19?_w{
!7~^B$#45!49?GOO?O_Cgc?GG?[GOCSW__@@B$#46!45?o[Y@B@Bo!38?@$#47!38?_w!5~NB@$#
48!35?w~~^F$#49!29?_{!4~F-#1!120?O$#3!118?GG$#4!124?_$#6!121?O__$#7!115?CCK$
#10!109?o__@AA$#12!108?O??@A$#13!104?C?WO??@$#14!103?KGG$#16!48?AA!4?CC?G!4?
G?@!27?G$#17!82?`!9?_!5?_$#18!68?A!14?A!7?G$#19!50?A!13?_??O!4?C!12?A??S???@
`O?A?@CEEC$#20!46?Aa!4?CC!9?@!8?__?G?oo??@??E??CGGG??O??@`?A$#21!56?G!4?_!4?
AA!11?`_!10?OO$#22!46?@?_!7?C???O!9?C??Ow?O?@?@?A$#23!51?A!6?C!4?G!4?O??C!4@
?A???cCC?KKG?OO???``_AA$#24!47?@!4?AA?G?C?SC@`_G???CK???G?_`@AAA$#25!52?__??
?OO__CEEAACC???GG??O!5?A$#26!51?OXXpoo_`BB$#27!45?B_?@wp@$#44!16?o{!9~^B$#45
!49?@Gg??IBBBA??A??CCGGG?WOO$#46!43?az{S[[CCC!13?G???O$#47!37?_x!4~\C?G$#48!
32?o}~~~^E$#49!27?_{~~~N@-#1!114?_??C$#2!120?GG$#3!112?__?AA$#4!122?OOP@@A$#
5!124?___?A$#6!118?CC$#7!109?OOO@@@$#10!108?GG$#12!106?KG$#13!103?ECC$#14!14
?G!84?__?A$#15!14?O!70?_!5?C!7?A$#16!46?O???__?_!14?@!12?O???@!7?G??O$#17!88
?A???O???_O??BA$#18!54?@!9?OO!10?_gG!7?AA$#19!14?_!34?@?@@!14?G!7?C@!8?C??G!
4?OG?@``@$#20!45?O?OP!4?@!4?A??G?C???@???A!4?G@`_o_A_DA?!4C?G??O$#21!54?_!7?
OO???_AAA!5?!4O??_AA$#22!45?GG@!7?@C??O???_?@@?_?C??CGW!5?@@@$#23!49?_@???A?
?E!6?C???GG??O?C!5?AA??_?C??GGG??O$#24!48?_??AA??c___igoc?___CCC?KKWO!4?@@$#
25!58?W?PBB?@??A$#26!46?C!4MKC?SWXX?@???B?AA$#27!43?B\FB!5?GG$#28!129?CC$#30
!131?GG$#32!133?O$#35!134?o$#37!135?__$#44!15?w!9~^B$#45!50?OOOUG???@?A???AC
C???G$#46!42?y{a___?O$#47!35?_{!5~D$#48!15?A!14?o{~~~^B$#49!15?C!9?_{~~~NB-#
1!113?O`@@$#2!116?_?AA$#3!112?O$#4!120?CC$#5!122?GGWOP@$#6!115?_?A$#7!108?CG
GG$#10!106?EC$#12!102?_AAA$#13!99?___@@$#14!12?W@!80?C?OWOP@@$#15!88?_C!6?G$
#16!13?E!55?O??@??A!6?_?O??_@?A$#17!12?_!34?G!25?G!8?G??Q!5?AGC?G$#18!59?@`!
5?G!13?GWOo_``@AA$#19!46?G??G!29?C?@!8?C?CGG$#20!13?G!30?CKC???GG??@O??A??`C
??G!4?C@??AC?COW?_?@@?AA$#21!43?C!13?A!4?_???OOO?_??A!6?O$#22!47?C!4?GIIEEC!
6?GO!4_AaECC?C?G$#23!48?G??O??_!9?A!4?C??_?GG?OC???@!8?C$#24!13?O!30?G!8?@??
OOSCCC@`o@BA??@C!4?GG$#25!50?C@_???GG?WG?GG?_?@BB$#26!47?_aA@EECCG??G?OWOO$#
27!40?cc}wo_BB@?a$#28!126?__bA$#29!130?A$#30!131?CC$#32!132?GG$#35!134?WOo$#
37!136?@__$#38!137?@B$#39!139?AE$#40!141?CKWG_O$#44!14?w!8~N@$#45!13?_!31?Oo
OSt?_@_!10?@A$#46!39?EYZ@BBB!4?O$#47!33?_}!4~x@$#48!14?@!13?o}~~~^@$#49!14?E
!8?o}~~~N@$#51!144?OO__-#1!110?CGG$#2!113?OOO_@$#3!109?C$#4!117?_`AAE$#5!122
?CKGG$#7!104?_?AAC$#10!101?___@B$#12!100?OO@@$#13!98?OW$#14!10?OA!79?_C???CG
G$#15!85?g_$#16!45?A?C?CC!5?G??_!5?@!12?A???S???Oo__@?A$#17!10?_!55?C!12?A!5
?@??OA_??A?CG$#18!43?_??A?C!12?AA!9?o`D@!6?GWWO$#19!11?C!31?AA!24?G!16?@@??A
??CCG$#20!42?_???C???GK???O?H@!6?C@?G??o???_?ACCC!7?@@?A$#21!55?_@AaAI???C??
?O?o??AaA$#22!40?_A@?_C_aI!4?_oCECKKCC?C??WW?o??B???A$#23!11?W@!28?_A!9?C!8?
OO???_`??A!4?CC?GG?C$#24!41?@?@C!4?G??OSC?__???GKWO???_@?A!5?C??GG$#25!48?_a
_o_??@!8?GW!4?@@$#26!45?OXXPORBABBA$#27!39?QRGWWXg???@$#28!128?@$#29!126?OO_
@@$#30!129?_AAA$#32!132?CCKG$#35!136?W$#37!137?Op__$#38!139?@BEA$#39!142?CKK
?_$#40!145?WOoa_$#44!14?B!6~^B$#45!45?@!6?@$#46!11?_?N!24?okKSCC!24?@$#47!12
?}o!18?}!5~N@$#48!14?_!11?o!5~@$#49!14?[!6?_{~~~N$#50!151?A??G$#51!147?@@BEK
[Woo__-#1!109?ACC$#2!112?CGGO$#3!106?_bA$#4!116?Oo@@B$#5!118?__?AAC$#7!104?O
`@$#10!102?OO$#12!99?CGG$#13!97?CCG$#14!8?OA!83?_AAE$#15!87?G??O?_@$#16!44?@
!18?@!6?@!8?CECG??GWO?P@@$#17!73?G!5?_?A??CO???__?BA$#18!47?@!8?G?CCC!5?A!4?
_!4?A?DA!8?O$#19!8?_C@!32?@?@!17?_!5?C!6?O!14?_$#20!46?@?B!4?A!4?OO??`G!4?S?
??hooQ__!4?CKG$#21!46?A??C!4?IIQQ??_@EEAA!4?OWO??@?BA$#22!45?A???@@_?GPp`__?
@E!11?@??@$#23!9?GA!31?@!21?G??O???@???_??_$#24!9?o!33?___?A???C?__??@???_??
CCCKGWG???@$#25!46?__c_c@xP!4?A`$#26!43?AAC[S!4W!6?@AA$#27!10?CO??C!23?CCY^]
[[W?G$#29!124?CGGWO$#30!129?@$#31!130?`@$#32!129?_?AAE$#35!135?K$#36!134?C?G
$#37!137?Wop`_C$#38!141?BBEG$#39!144?CKWwO?_$#40!148?`bBCGO$#44!15?B^~~~B$#4
5!15?o!21?!6_!22?GG$#46!10?wno?I!16?_?___o[ZZD$#47!12?N~o!15?{^~^^^NB$#48!14
?@G!8?o}!4~B$#49!15?C_???{~~~N@$#50!157?@?EQ?W_?_$#51!151?AEKWxrafGK[_Oo-#1!
107?```A$#2!111?ACCC$#3!106?O$#4!115?GGO$#5!118?O_``$#7!103?GWO$#8!102?G$#10
!100?CK$#12!96?_?AC$#13!95?_BA$#14!6?O!83?G?pp`B$#15!7?A!53?C!20?@$#16!48?@@
!12?C!13?G??A?`?CAC$#17!6?_C!58?G!15?c?C?KK?WOO$#18!50?@@!14?@?AA!10?BAAA$#1
9!7?G!71?O!8?G$#20!57?A!7?@?G!7?G_`o`_$#21!64?@??A??C???GOOO@$#22!69?C???GO$
#23!7?O@!19?@!23?@???A!6?C!7?OS??`@$#24!7?_M!46?@@@AABBABC?CCKG?CGO$#25!8?O!
49?@@??@?AAA$#27!9?|?G$#29!122?AAECK$#31!127?GWOp$#33!132?A$#34!131?``$#36!1
33?AECKW$#37!138?Wopa$#38!141?@BEE?O$#39!145?KKWpo_C$#40!149?@BBEM[wxqc$#44!
17?@FFA$#45!8?_!7?A?__!33?@@!10?C!4?GG$#46!9?A~v~~~tswO$#47!15?IG$#48!16?@CG
!5?!4@$#49!17?A??DBBB$#50!162?G?@BBCGO_$#51!157?@BFM[sxqcKYs_?__$#54!169?GWO
-#1!106?GOO@$#2!109?_``A$#3!104?KG$#4!113?AECG$#5!116?CGGOO`$#7!103?C$#10!10
0?AEC$#12!98?AA$#13!95?Pp``$#14!4?O!87?GWO_$#15!4?_!80?@$#16!84?@?A$#17!5?E!
80?CE??C$#19!17?KW_!62?AA!4?CKGGO$#20!5?W@!15?G!59?@@AA$#22!5?_M$#23!16?A??O
???O_!54?@@@$#25!6?o$#26!8?C!10?KWWo$#27!7?N_BVFk@$#29!122?`BAE$#31!126?CKGW
O`$#34!131?O`b@$#36!134?AEMKWWoo$#37!140?@@b@$#38!143?AEMKWwo__$#39!149?@BBF
MW?G??_$#40!154?C[ppbFN][_A?_!5?GO_$#45!7?oZ{gw??E[W?@Bec?_$#46!12?R}xbdre$#
50!163?O_@??IPa@A@GO_$#51!163?HPeN]SkXudKUcWo_$#54!173?A?G-#1!108?O$#2!110?o
`@$#3!107?GG$#4!112?_@AA$#5!116?CCKGW$#6!109?O$#7!105?CG$#10!102?AEC$#12!99?
@BA$#13!98?@$#15???A$#16???C@$#17??o$#19!18?G_$#20???WA!22?CGO_$#21!26?O$#22
???_SB$#23!17?GOO?CG??@A$#24!20?A!4?O_$#25!4?g!20?ACgO_$#26!5?{~`!4?O{G!9?AK
GO_$#27!7?]Ny`Lg?Ro$#29!121?Op`bAE?G$#31!127?CCGWOP__$#33!140?G$#34!132?_@BF
EMKO_$#36!139?GOpoa$#37!142?@@FEK[Woo__$#38!149?@@BFMIWwwo_$#39!154?CC?@AE?G
?cG!18?_$#40!158?@@FE[WprcGW|wCgO_@??_?{wo$#42!178?O_$#45!8?oD]qFBcGwoBN[wrf
L$#46!15?FFFc?_@$#50!167?@!6?GObFI[$#51!166?BEE?@rFNUkWoDA-#4!113?@@$#5!115?
AAECK$#15?K$#16?O@$#18?_M!22?OA!7?C???_$#19!24?G$#20!25?@??GO$#21??oo!21?GW!
4?GMCwwo_$#22???N$#23!20?@B?C???DA???O$#24!22?G!4?_??c@?O$#25!16?W??_!5?AC?@
a$#26!4?~}}||_@Ysa???O!7?C?O_@AE?G$#27!5?@@AA^MCJK@@$#29!120?GWOo``@CA$#31!1
26?AACKKWwoo`D$#34!133?@@AAEKKWwo__$#36!142?@@BFEK[woo_$#37!150?@@BFM[{wo__?
?_$#38!157?@@BFL][wo_!6?_!10?_{o$#39!161?A??@BFM[wocgWo__G___oow]$#40!167?@A
CHRFFM\ZtK\[@B$#42!178?O?BMKF$#45!10?o`?P}{djqFMwprf??GO?@$#46!15?AACLWoCA$#
50!177?A$#51!178?BA-#16?@!34?A??G$#17!21?_$#18?E!25?_!6?_H??C@??C_$#19!21?@A
$#20?w!17?GO?c??GO!18?O$#21!16?O???GO?_!5?__`IC[op`BEAKOWo__$#22??~z!9?oA?__
$#23!30?S$#24!17?ACC@A@?S`AShA???O???A_?GOG$#25???C!7?_??cW@!6?@@!4?O?CCG!6?
C$#26!4?!5~n^SxNXCG??aCKWOaA??O@BA$#27!9?O_GE!5?A$#29!125?@B?C$#31!127?BAEKK
WwppbBAE$#34!137?CCG[Wwpb`CKWWo??_$#36!145?ABACCGpbFNM[wwo_GWo__!23?_$#37!15
8?@BFFEKXYogWw{go_???o??_Go__ww~{$#38!165?@FFFE@VK[x}{Gwx]uK^^FF$#39!172?BBE
@BFFE@@B$#41!189?O$#45!11?B???bE[xPa??I?CKG$#46!17?@-#15!22?@$#16!27?O!11?_!
4?@!6?SO!4_$#17!20?GO!31?G?O$#18!21?G?@!12?HA?C?A??G@a_DEKGGO$#19?C!17?C$#20
?B!16?AAC???ACG!4?C???_!6?O!11?O$#21!21?CK?`?BESppqfMKWOpbBEKKWoo@BA$#22??B!
6?FMo?_???@@!4?C$#23??_!13?O_$#24??K_!7?G?@AKGO_GO`Q_GO_G??A???O?_$#25???[_!
6?C?Oc?A??@???G?BC??G?@$#26???B^!4~wO?JMW?CKO?bA?OO_??G$#27!10?`@C??O$#31!13
5?@BBFMM[wwp`_?OWO$#33!156?A!5?O!4?_!5?_!16?sO$#34!143?@AAFNMCgxrffM[wxoog?g
__$#35!180?Ga$#36!157?C?BFFMU\ZvN^}{{wWwww_O__!4?oww?cG$#37!170?BBFFFDAFN]FL
vN^NFFA$#38!176?@??@$#41!175?ACW_?OOGo_???|ZB_$#45??O!8?Ao?@b@AGo$#46!16?_?C
-#9!66?O$#11!62?G$#12!66?___$#13!62?CGWO$#14!57?A_CEC$#15!49?C!4?G_O?BA$#16!
50?E??W?O$#17!45?@!5?G???@``$#18!24?@ACGO!8?gq_DAGOWoo`bA?CK?O$#19!18?@A?G$#
20!12?_!9?O!8?AC_???@??_??C??@A$#21!25?@BFM[wpbFEKWO@BACCG$#22!4?@C!4?PCG?@A
C!6?_$#23???CO!8?_??GoaCK?@ACGO_$#24???@G!6?_?B?C?@?HOC??_!5?@???GO$#25!4?CR
OGbCI?DS__??O__?IC$#26!4?A?BB[x_B?GO?BEGO@BCWO_$#27!6?CS!6?C$#31!144?@BFNM][
wo`a?KGS_$#32!174?@ACW$#33!167?AbAECog{py_owo_??_?o{{}~~$#34!150?_@BEDNQshZv
n^}|zvk[ww_$#36!167?@?C@ZNVAK@FNFN^}z]~N@B@$#41!182?@C@??A$#45???A?gg_?ACOQ?
IX_G??A???GO_$#46!11?G!4?O?C??_-#7!73?CC$#9!65?GO$#10!67?O``bAA$#11!61?E$#13
!62?CKG$#14!57?@_bA$#15!55?G?O$#16!15?C!14?_??C??O?@!4?I??g??ACAGCWOO$#17!56
?__@$#18!31?g__DEKW_PaDECCW?p`@ACCG$#19!13?@A??_@AC?_$#20!11?GO_!6?GO!8?K@Q?
?G!8?G!4?_$#21!19?_!5?g_??KOO@BA???O_@A!4?O$#22!11?S???A_!11?K$#23!5?@?G??C?
_?@GWO_D!9?A$#24!9?EI?GA?PC?A?BC@Ac@Qd@O$#25!7?FF??_@O__?@CGoB?CW?@AA$#26!10
?pBEKW?BEGO??E??O$#31!151?@BBBDMKXjT_C??A$#32!171?G??BA$#33!167?O`BES{~{|!6~
}{!7~^$#34!154?CIOo_OaNZ}|xvn]{xbB$#36!182?@B$#45!6?B?Wx!4?C??GO??_?W$#46!22
?G-#1!76?C$#2!78?GG$#3!71?_??AC$#4!80?OOo$#6!77?K$#7!67?OOO`@@A$#8!65?GG$#9!
63?CCC$#10!67?G$#11!58?_$#12!63?A$#13!59?__BA$#14!56?G?P@@$#15!51?@??C$#16!2
7?C!9?O?@??@?GC?G`_A?EC$#17!13?_!40?GGOO$#18!21?C!4?o_?GOg@b_?MKW__`?ECGWOO@
@A$#19!13?@A?Oo!32?_$#20!20?A?_?_?A!7?C!4?OOA$#21!13?C_`eNGo`bEMWx@AFEKOo?BE
!4?@?A$#22!13?O@A??Q!8?@$#23!9?@A???CG???D???O$#24!10?@CHA?O!4?WOH?C$#25!11?
BA?G???CG$#26!12?CGO?@$#28!83?___$#31!160?@?@??@$#32!169?@EK?@AQ?@$#33!167?O
@?Ho{}|l~}!11~^F$#34!158?@BEN]}|yvN}}oBB$#36!167?_-#1!71?___AA$#2!76?ACC$#3!
68?GWOO@@$#4!79?KGG$#5!82?O$#7!65?CCG$#8!64?E$#9!60?_?B$#10!61?_?A$#11!56?C$
#12!59?O?@$#13!57?GO?@$#14!53?CEKG$#15!32?@!12?A???_PAA$#16!14?@!18?@_??I?G_
?a@C???GO?@$#17!25?@!14?G!9?__@A$#18!15?ACGQC@A_GYcHQDM[Ogo?BECCO?`?AAC$#19!
19?_!21?O!5?OO$#20!27?@!6?A???G?O?@???KG$#21!15?@BFKWopFFCWo_a??GO?@$#24!20?
G$#28!83?OO`@$#30!86?_@@!82?G$#32!170?CO$#33!165?C??HAIc!15~^B$#34!165?@BA?@
@B$#35!87?_AA$#36!164?@AK\u{o$#37!90?A$#38!91?E$#39!92?C$#40!93?KC?O$#50!94?
GGGO?_?O???_$#51!97?GOO$#54!100?o!4_-#1!70?GOO$#2!74?_`@$#3!67?CKG$#4!76?AAA
C$#5!80?C$#6!73?O@$#7!61?___AAE$#10!60?OO@@$#11!53?_$#12!57?GGW$#13!55?ECC$#
14!51?p`BA$#15!27?A!21?O$#16!21?A???O`??_?OCH??DCCGW?o_A$#17!38?GS?_@?@EAGGG
O$#18!22?A??GWpaDGGWopbAA???O$#19!46?CC$#20!20?@???G!18?@$#21!21?@@FEC??@AEC
$#28!81?KGG$#30!84?OO$#33!170?@F^!12~NB$#35!86?o``$#36!169?@A$#37!89?`$#38!9
0?B!81?_$#39!91?AA$#40!94?CC$#41!171?G$#42!93?E!75?AC$#50!96?GC?O??`O!4?_C??
CC?A!18?OOO$#51!96?C!4G$#52!108?C!5?C??G?_cOOO???gg!4_!6?O??!4_??__o___O!5?G
$#53!116?G?G?OGg?oooO!5?!7_!6?__!6?!4_$#54!100?OOO`pbbbBBEEIII[SSSC!8?!6O???
OO!12?OOO?OOO$#55!119?WG_?gGGG!13?__!16?oOOG$#57!168?A$#58!159?__owW?CC$#59!
163?_wwwKC$#60!167?ow{wO$#61!171?_-#1!64?__??CC$#2!71?GG$#3!62?Oo?@AA$#4!73?
OO_`@B$#6!70?K$#7!60?GW?@@$#9!56?AA$#10!57?CCK$#12!55?A$#13!50?OOo``@$#14!45
?_?EGKG$#16!27?@??DG?GhO_DC$#17!39?GC?_``BA$#18!28?@BAEKOO@BAAC$#19!41?WOO!4
?C$#20!35?_$#23!40?G$#28!77?_?AACC$#30!83?K$#33!173?@F^!7~N@$#35!84?GG$#37!8
6?W$#38!87?Oop!83?AG$#39!90?`@$#40!91?_bAAEA$#41!175?_$#42!93?@!52?OOO??!4O$
#50!96?CCKKCOGGGo_O?A??_@??G?AE!4?CC$#52!105?@?_O???C??!4C??GGGXXOwOO@H@?G!4
?BHZPC$#53!120?W!4?_G?gBwoo``bbbfCECEBFNNFffBFFB@DB$#54!100?GGOOO?P@``bbBEEA
AIGGCSSS_??@!6?CC!4?O$#55!126?`?@gAAIYQOSSOo!7_g$#57!142?GWWO???Os??ceqO$#58
!148?GGGggGGGk~~^FB$#59!159?_w{~~^B$#60!164?_{!4~^$#61!170?_~~{o-#1!62?GOO@@
$#2!66?__AACC$#3!61?G$#4!72?KGGO$#5!76?O$#6!65?_?@$#7!58?ECC$#10!54?__BA$#12
!51?GWO@@$#13!48?CCK$#14!40?GCGOp_BAA$#15!35?@??@$#16!36?@@A?C$#17!37?A?E!5?
@$#19!41?GO$#28!77?o``@$#30!80?!4A$#32!83?C$#33!176?B!4~F@$#35!84?C$#37!85?K
G$#38!87?GO$#39!88?GO?_$#40!90?OPp`B`?C$#41!176?K$#42!142?!10G$#43!175?@O$#5
0!95?AAAEAKKCCWWGwo@@O!4?@???G???A!6?CC$#51!94?_$#52!99?C!8?@_??q__??@DC?CCE
KK]G_@?@$#53!115?C??A??G?GO???GwwWwg__g`hw@`@?APP$#54!102?GG??O??Oo`@BBbee?A
EAA??Q?CCCD?@?@$#55!122?G!4?OO??_?@IJBIAAQQ??O?__$#57!133?!6ODkKCDD??!5OWWW$
#58!142?qq_eEF!7f~^B$#59!156?_{!4~N@$#60!162?o}!5~N$#61!169?o!5~}_-#1!60?CCC
$#2!63?GGOO@@@$#3!58?AA$#4!67?___AACC$#5!74?K$#6!62?G$#7!55?_``$#10!53?WOO$#
12!49?CCKG$#13!45?@?BAA$#14!46?@$#28!75?GGOO$#30!79?O`@A$#33!177?@^B$#35!81?
_`AA$#36!177?}$#37!85?E$#38!86?C$#39!87?CK$#40!89?GGWG?`$#42!90?O$#50!92?OoO
p`bbbCC?GGCCC??GW!4?OO!5?_$#52!102?E!7?___?O___CEAEBJ?DCS!4KA_`??@$#53!114?`
??@a@C?CCFAAG!4?KWWXGG??cC@D$#54!100?AA?CCG!4WO@PP?R@?@?``_!5?!4A?AAA$#55!11
3?_??AA?_!4?GGGA!5OCCcCCCD@@K$#57!136?poXyGYAAECC!5K$#58!132?_!5?_?Q_owxzz!5
rNNB@$#59!152?oo{}!4~N@$#60!160?o}!5~^B$#61!167?_{!8~-#1!60?AA$#2!63?CGGO$#3
!59?@$#4!67?OO``@A$#6!62?C$#7!57?@@$#28!73?AEC$#30!76?CG$#35!78?GW??@!94?A$#
36!176?G@$#37!80?OOO@@$#38!82?__?B!90?C$#39!84?__AA$#40!88?EECKC$#42!136?___
``@!33?_$#50!93?GWW?@??BB`_!4?A?S?C??_?G$#51!92?G$#52!97?_?O!4?C!6?O??`!4O?@
_cEAFAIAI??O@$#53!119?po@A_c_@?CDMkKSKK!4CEC$#54!96?OOp`__AFAEEMKKGKWWWHh`JA
AOPPOO_`h_`@$#55!118?_??A??@?CC???AbiqQ!4A$#57!135?_XXHG?a!6bA$#58!138?OOWW!
5[W|^NB$#59!147?C?_o{!5~NB$#60!157?o{!6~NB!9?A$#61!165?o{!8~^@-#5!71?@@$#28!
73?@AAEC$#30!78?CGGW$#35!82?OO$#37!84?o$#39!85?`$#40!86?``b$#42!141?O$#50!89
?ACECG?C?OGG!5?@!13?@$#51!90?A???K$#52!103?O???DCC?ACCSKKGG??OOO?O$#53!110?C
C???O???WWggGP`p`dbbAB$#54!93?C?GGGOOppPbbAbabAAGIAA?OSCCD@@@???G$#55!102?_?
?_!7?GG???O__??aiIIQYSOtsppwc__$#57!130?C?GIIAYYZPP@ppp@@@$#58!133?CCD@DCmmm
MMMy??@$#59!145?C}}}!4~^F@$#60!153?_w}!7~F@$#61!163?w}!8~NB-#40!87?@$#42!140
?!4G$#50!89?@@@?ACA!19?_!5?A$#51!88?@?AA??A$#52!104?G!4?O??@@A?!4C!4?@$#53!1
04?O?!5_AAEGC!4?KK!4GWwO??C$#54!92?AC?CKKK[WWwH@@PRRB@`c__HIIAAA?!8C$#55!103
?o_o!4?EC??DA??GW!4Oop`@hhNBB$#57!129?QOOCC!6K!4CGG$#58!130?_gwz!5rR!4BD$#59
!139?_!4oqv~~~^F@$#60!149?_w}!8~N@$#61!160?o}!6~^NB@-#52!109?@@@!18?@$#53!11
2?BBAAECA?DHKC??C$#54!105?@@@$#55!108?BAAECCDLHHHXQQRqAAAEEA?B$#57!117?ACE?C
?GKK!7?BBB!4AEE$#58!120?G???oowww{}{^[K???CC$#59!132?__o{||!4x~~^NF@$#60!144
?_ow}!8~^^B$#61!156?__{^^NNFB@@-#58!127?@$#59!128?!4@!10BFFFB$#60!145?C!7B@@
@-\
HELIX_LOGO_EOF
            ;;
    esac
}

# Logotype colors match the wordmark: Helix in blue, Screen as a red to
# orange ramp. 16-color terminals get the nearest ANSI colors.
_logotype() {
    if [ "$UI_COLOR" = 256 ]; then
        printf '\033[1;38;5;33mHelix\033[38;5;197mSc\033[38;5;203mre\033[38;5;209me\033[38;5;214mn\033[0m'
    elif [ "$UI_COLOR" = 16 ]; then
        printf '\033[1;34mHelix\033[1;31mScr\033[1;33meen\033[0m'
    else
        printf 'HelixScreen'
    fi
}

# Ask the terminal what it can draw. One write carries a kitty graphics query,
# a cell-size request (CSI 16 t) and DA1. Every terminal answers DA1, and
# answers in order, so its reply ends the read with nothing left unread; the
# timeout only matters for a terminal that answers nothing at all.
_logo_probe() {
    _LOGO_REPLY=""
    _lp_tty="${HELIX_TTY_DEVICE:-/dev/tty}"
    _lp_old=$( (stty -g < "$_lp_tty") 2>/dev/null) || return 0
    stty -echo -icanon min 0 time 10 < "$_lp_tty" 2>/dev/null || return 0
    printf '\033_Gi=31,s=1,v=1,a=q,t=d,f=24;AAAA\033\\\033[16t\033[c' > "$_lp_tty"
    while _lp_in=$(dd bs=64 count=1 < "$_lp_tty" 2>/dev/null) && [ -n "$_lp_in" ]; do
        _LOGO_REPLY="$_LOGO_REPLY$_lp_in"
        case $_LOGO_REPLY in *"[?"*c) break ;; esac
    done
    stty "$_lp_old" < "$_lp_tty" 2>/dev/null
}

# Pick the logo from a probe reply: kitty, iterm, sixel or text. Also sets the
# cell size in pixels, guessing 9x18 when the terminal does not say.
# HELIX_INSTALL_LOGO=kitty|iterm|sixel|text forces the mode.
_logo_pick() { # reply
    _LOGO_CW=9; _LOGO_CH=18
    _lk_r=${1#*"[6;"}
    if [ "$_lk_r" != "$1" ]; then
        _lk_h=${_lk_r%%;*}; _lk_r=${_lk_r#*;}; _lk_w=${_lk_r%%t*}
        case "$_lk_h$_lk_w" in
            "" | *[!0-9]*) ;;
            *) [ "$_lk_h" -gt 0 ] && [ "$_lk_w" -gt 0 ] && { _LOGO_CW=$_lk_w; _LOGO_CH=$_lk_h; } ;;
        esac
    fi
    if [ -n "${HELIX_INSTALL_LOGO:-}" ]; then
        _LOGO_MODE=$HELIX_INSTALL_LOGO
        return 0
    fi
    _LOGO_MODE=text
    case $1 in
        *"_Gi=31;OK"*) _LOGO_MODE=kitty; return 0 ;;
    esac
    case "${LC_TERMINAL:-}:${TERM_PROGRAM:-}" in
        iTerm2:* | *:iTerm.app) _LOGO_MODE=iterm; return 0 ;;
    esac
    case $1 in
        *"[?"*c)
            _lk_da=${1##*"[?"}
            case ";${_lk_da%%c*};" in *";4;"*) _LOGO_MODE=sixel ;; esac
            ;;
    esac
}

# Draw an image with the logotype and subtitle to its right. Rows are
# reserved first so the image cannot scroll the screen out from under the
# saved cursor position the text is placed from.
_logo_image() { # mode subtitle
    _li_w=${_LOGO_PX% *}; _li_h=${_LOGO_PX#* }
    if [ "$1" = sixel ]; then
        _li_rows=$(( (_li_h + _LOGO_CH - 1) / _LOGO_CH ))
        _li_cols=$(( (_li_w + _LOGO_CW - 1) / _LOGO_CW ))
    else
        _li_rows=10
        _li_cols=$(( (_li_rows * _LOGO_CH * _li_w / _li_h + _LOGO_CW - 1) / _LOGO_CW ))
    fi
    _li_i=0
    while [ "$_li_i" -lt "$_li_rows" ]; do printf '\n'; _li_i=$((_li_i + 1)); done
    printf '\033[%sA\033%s  ' "$_li_rows" 7
    _logo_art "$1" | tr -d '\n'
    printf '\033%s' 8
    _li_mid=$(( (_li_rows + 1) / 2 ))
    _li_i=1
    while [ "$_li_i" -le "$_li_rows" ]; do
        if [ "$_li_i" = "$_li_mid" ]; then
            printf '\033[%sC%s' "$((_li_cols + 5))" "$(_logotype)"
        elif [ "$_li_i" = "$((_li_mid + 1))" ]; then
            printf '\033[%sC%s' "$((_li_cols + 5))" "$2"
        fi
        printf '\n'
        _li_i=$((_li_i + 1))
    done
}

print_banner() { # version channel
    if [ "$UI_TTY" != 1 ]; then
        printf 'HelixScreen installer %s (%s)\n' "$1" "$2" >&2
        return 0
    fi
    _pb_sub="$(printf '%b%s · %s channel%b' "$DIM" "$1" "$2" "$NC")"
    [ "$UI_UTF8" = 1 ] || _pb_sub="$(printf '%b%s (%s channel)%b' "$DIM" "$1" "$2" "$NC")"
    printf '\n' >&2
    _LOGO_MODE=text
    if [ "$UI_COLOR" != 0 ]; then
        # Graphics go to stderr, so only a terminal there is worth asking.
        _LOGO_REPLY=""
        [ -n "${HELIX_INSTALL_LOGO:-}" ] || { [ -t 2 ] && _logo_probe; }
        _logo_pick "$_LOGO_REPLY"
    fi
    case $_LOGO_MODE in
        kitty | iterm | sixel)
            _logo_image "$_LOGO_MODE" "$_pb_sub" >&2
            ;;
        *)
            if [ "$UI_UTF8" = 1 ] && [ "$UI_COLOR" != 0 ]; then
                _pb_i=0
                _logo_art "$UI_COLOR" | while IFS= read -r _pb_line; do
                    _pb_i=$((_pb_i + 1))
                    case $_pb_i in
                        6) printf '  %s\033[0m   %s\n' "$_pb_line" "$(_logotype)" ;;
                        7) printf '  %s\033[0m   %s\n' "$_pb_line" "$_pb_sub" ;;
                        *) printf '  %s\033[0m\n' "$_pb_line" ;;
                    esac
                done >&2
            else
                printf '  %s\n  %s\n' "$(_logotype)" "$_pb_sub" >&2
            fi
            ;;
    esac
    printf '\n' >&2
}
