# Copyright (c) 2025-2026 356C LLC
# SPDX-License-Identifier: GPL-3.0-or-later
"""
Glossary module - derives translations/GLOSSARY.md from the committed YAML.

The glossary is the source of truth for terminology *consistency*: canonical
per-language renderings of recurring UI terms. Translators (human or agent)
reuse the listed word instead of coining a new one for an already-translated
concept. Values are derived from the YAML so the doc never drifts from reality.
"""

from __future__ import annotations

from pathlib import Path

import yaml

# Locales in column order (en is the key, so it is not a column).
LOCALES = ["de", "es", "fr", "it", "ja", "pt", "ru", "zh"]

# Curated anchor terms grouped by theme. Each entry is an English key that
# exists in the YAML; its committed translations define the canonical rendering.
# Add a term here when a recurring concept needs to be pinned across locales.
GLOSSARY_GROUPS: dict[str, list[str]] = {
    "Hardware / filament path": [
        "Filament", "Nozzle", "Bed", "Heater", "Chamber", "Extruder",
        "Fan", "Fans", "Spool", "Printer", "Vendor",
        # Position nouns: each backend's own word for one filament position, plus
        # the plurals lane_range_label() uses for a range.
        "Slot", "Lane", "Gate", "Feeder", "Tool", "Toolhead",
        "Slots", "Lanes", "Gates", "Feeders", "Tools", "Toolheads",
    ],
    "Actions": [
        "Save", "Cancel", "Close", "Delete", "Edit", "Retry",
        "Install", "Uninstall", "Update", "Print", "Pause", "Resume",
        "Configure", "Restart",
    ],
    "Status": [
        "Connected", "Disconnected", "Unknown", "None", "Off", "On",
        "Available", "Enabled", "Disabled", "Error", "Warning", "Settings",
    ],
    "Progress": ["Loading...", "Downloading...", "Detecting...", "Checking..."],
    "Connectivity": ["Bluetooth not available"],
}

_HEADER = """<!-- AUTO-GENERATED by `make translation-glossary` (scripts/translations/glossary.py) -->
<!-- Do NOT hand-edit the term values; they are derived from translations/*.yml. -->

# HelixScreen Translation Glossary

Canonical per-language renderings of recurring UI terms. **When translating,
reuse the exact word listed here** — never coin a new word for a concept that
already has an established translation. This file is the source of truth for
terminology consistency across the nine locales, and is consumed by the
translation tooling (`make translation-sync` reminds you to consult it) and by
translation agents (the relevant column is injected into their prompts).

## How to use

- Translating new strings (human or agent): look up each recurring noun/verb
  here and reuse the listed rendering. For terms not listed, `grep` the target
  `translations/<lang>.yml` for the English word and reuse the dominant existing
  translation rather than inventing a new one.
- This file is regenerated from the committed translations. To pin a new
  recurring term, add its English key to `GLOSSARY_GROUPS` in
  `scripts/translations/glossary.py`, make sure it is translated in every
  locale, then run `make translation-glossary`.

## Ambiguous terms (resolved)

- **Position nouns** (`Slot`, `Lane`, `Gate`, `Feeder`) all name one filament
  position, and the UI uses whichever word that printer's hardware uses: AFC says
  Lane, Happy Hare says Gate, Snapmaker U1 says Feeder, Bambu-style AMS/CFS/QIDI/
  ACE say Slot. They must render as FOUR DISTINCT words in every locale - if two
  collapse, the backend's noun buys nothing. `Tool` and `Toolhead` are the same
  idea for the printing end rather than the filament position.
- **Loanword policy for these four.** `Gate` is Happy Hare's English term of art
  and stays untranslated in de, es, fr, it and pt; ja transliterates it (`ゲート`),
  zh translates it (`通道`), ru transliterates to Cyrillic (`Шлюз`). The evidence:
  Happy Hare ships no translations at all and its own touchscreen frontend
  hardcodes English "Gate", mainsail's German translator kept and compounded it
  (`Gate-Zuweisung`), and Bambu's own catalogue keeps English `slot` in de (23/23),
  it (22/22), pt (20/22) and fr (18/24) while only es translates it (`ranura`).
  So those locales demonstrably take English hardware nouns in this domain.
  Gate and Lane in es, fr, it, ja and pt rest on NO direct evidence - there is
  almost no native-language writing about these projects - so they are defaults,
  not findings, and a native speaker may overturn any of them.
- **Do not reason from OrcaSlicer or wiki.bambulab.com.** Orca is a fork with its
  own catalogue and disagrees with Bambu (it ships fr `Emplacement` and pt_BR
  `Espaço`, neither of which Bambu uses). The Bambu wiki is self-declared machine
  translation for every locale but en and zh. Bambu Studio's `.po` is the
  authority, and it must be counted in the `msgstr` - a raw file grep for "slot"
  mostly returns English `msgid` lines and overstates loanword use several-fold.
- **Plurals are fixed strings, never generated.** `lane_range_label()` renders a
  range as one plural noun plus the range ("Lanes 1-4"). Russian numeral agreement
  would demand `1 слот` / `2-4 слота` / `5+ слотов`, so the plural is a nominative
  header and is never agreed with either number. Italian does not pluralise English
  loanwords (`Slot`, `Gate` stay as-is); ja and zh do not inflect for number, so
  their plural equals their singular. None of these is an oversight.
- **Feeder** vs **Toolhead**: Snapmaker U1-specific. The U1 names where filament
  enters `Feeder` and the printing end `Toolhead` — two different words for the
  same 1:1 physical position, matching the U1's own firmware UI. Reuse each
  locale's existing `feeder`/`toolhead` rendering (established from other
  strings using those English words) rather than coining a new one.
- **Spool**: the physical spool noun — keep one rendering per locale.
- **Light**: ambiguous (theme "Light" vs LED light) — translate by context; not
  a fixed glossary term.

## Glossary
"""


def _load(yaml_dir: Path) -> dict[str, dict[str, str]]:
    data: dict[str, dict[str, str]] = {}
    for loc in LOCALES:
        with open(yaml_dir / f"{loc}.yml", encoding="utf-8") as f:
            data[loc] = yaml.safe_load(f)["translations"]
    return data


def generate_glossary_markdown(yaml_dir: Path) -> str:
    """Build the GLOSSARY.md content from the committed YAML."""
    data = _load(yaml_dir)
    header_row = "| English | " + " | ".join(LOCALES) + " |"
    sep_row = "|" + "---|" * (len(LOCALES) + 1)

    lines = [_HEADER]
    missing: list[str] = []
    for group, terms in GLOSSARY_GROUPS.items():
        lines.append(f"\n### {group}\n")
        lines.append(header_row)
        lines.append(sep_row)
        for term in terms:
            vals = [data[loc].get(term) for loc in LOCALES]
            if all(vals):
                cells = " | ".join(str(v) for v in vals)
                lines.append(f"| {term} | {cells} |")
            else:
                missing.append(term)
    if missing:
        lines.append("\n<!-- Terms not yet translated in every locale (skipped): "
                     + ", ".join(missing) + " -->")
    return "\n".join(lines) + "\n"


def write_glossary(yaml_dir: Path, out_path: Path) -> Path:
    """Regenerate the glossary file. Returns the path written."""
    out_path.write_text(generate_glossary_markdown(yaml_dir), encoding="utf-8")
    return out_path
