# Copyright (c) 2025-2026 356C LLC
# SPDX-License-Identifier: GPL-3.0-or-later
"""
Glossary module - derives translations/GLOSSARY.md from the committed YAML.

The glossary is the source of truth for terminology *consistency*: canonical
per-language renderings of recurring UI terms. Translators (human or agent)
reuse the listed word instead of coining a new one for an already-translated
concept. Values are derived from the YAML so the doc never drifts from reality.
"""

from __future__ import annotations

from pathlib import Path

import yaml

# Locales in column order (en is the key, so it is not a column).
LOCALES = ["de", "es", "fr", "it", "ja", "pt", "ru", "zh"]

# Curated anchor terms grouped by theme. Each entry is an English key that
# exists in the YAML; its committed translations define the canonical rendering.
# Add a term here when a recurring concept needs to be pinned across locales.
GLOSSARY_GROUPS: dict[str, list[str]] = {
    "Hardware / filament path": [
        "Filament", "Nozzle", "Bed", "Heater", "Chamber", "Extruder",
        "Fan", "Fans", "Spool", "Slot", "Printer", "Vendor",
    ],
    "Actions": [
        "Save", "Cancel", "Close", "Delete", "Edit", "Retry",
        "Install", "Uninstall", "Update", "Print", "Pause", "Resume",
        "Configure", "Restart",
    ],
    "Status": [
        "Connected", "Disconnected", "Unknown", "None", "Off", "On",
        "Available", "Enabled", "Disabled", "Error", "Warning", "Settings",
    ],
    "Progress": ["Loading...", "Downloading...", "Detecting...", "Checking..."],
    "Connectivity": ["Bluetooth not available"],
}

_HEADER = """<!-- AUTO-GENERATED by `make translation-glossary` (scripts/translations/glossary.py) -->
<!-- Do NOT hand-edit the term values; they are derived from translations/*.yml. -->

# HelixScreen Translation Glossary

Canonical per-language renderings of recurring UI terms. **When translating,
reuse the exact word listed here** — never coin a new word for a concept that
already has an established translation. This file is the source of truth for
terminology consistency across the nine locales, and is consumed by the
translation tooling (`make translation-sync` reminds you to consult it) and by
translation agents (the relevant column is injected into their prompts).

## How to use

- Translating new strings (human or agent): look up each recurring noun/verb
  here and reuse the listed rendering. For terms not listed, `grep` the target
  `translations/<lang>.yml` for the English word and reuse the dominant existing
  translation rather than inventing a new one.
- This file is regenerated from the committed translations. To pin a new
  recurring term, add its English key to `GLOSSARY_GROUPS` in
  `scripts/translations/glossary.py`, make sure it is translated in every
  locale, then run `make translation-glossary`.

## Ambiguous terms (resolved)

- **Slot** vs **Lane**: both name one filament position in a multi-material
  unit. Generic UI says `Slot`, and every locale renders it with its own slot
  term. AFC-specific screens keep `Lane`: they label AFC hardware and sit beside
  AFC's own `Hub`, so "Stopped between Slot and Hub" would read as nonsense.
  Translate a `Lane` string with the locale's lane word, not its slot word.
  Chinese is the exception in the other direction - it has never distinguished
  the two and uses the slot term throughout.
- **Spool**: the physical spool noun — keep one rendering per locale.
- **Light**: ambiguous (theme "Light" vs LED light) — translate by context; not
  a fixed glossary term.

## Glossary
"""


def _load(yaml_dir: Path) -> dict[str, dict[str, str]]:
    data: dict[str, dict[str, str]] = {}
    for loc in LOCALES:
        with open(yaml_dir / f"{loc}.yml", encoding="utf-8") as f:
            data[loc] = yaml.safe_load(f)["translations"]
    return data


def generate_glossary_markdown(yaml_dir: Path) -> str:
    """Build the GLOSSARY.md content from the committed YAML."""
    data = _load(yaml_dir)
    header_row = "| English | " + " | ".join(LOCALES) + " |"
    sep_row = "|" + "---|" * (len(LOCALES) + 1)

    lines = [_HEADER]
    missing: list[str] = []
    for group, terms in GLOSSARY_GROUPS.items():
        lines.append(f"\n### {group}\n")
        lines.append(header_row)
        lines.append(sep_row)
        for term in terms:
            vals = [data[loc].get(term) for loc in LOCALES]
            if all(vals):
                cells = " | ".join(str(v) for v in vals)
                lines.append(f"| {term} | {cells} |")
            else:
                missing.append(term)
    if missing:
        lines.append("\n<!-- Terms not yet translated in every locale (skipped): "
                     + ", ".join(missing) + " -->")
    return "\n".join(lines) + "\n"


def write_glossary(yaml_dir: Path, out_path: Path) -> Path:
    """Regenerate the glossary file. Returns the path written."""
    out_path.write_text(generate_glossary_markdown(yaml_dir), encoding="utf-8")
    return out_path
