// Copyright (C) 2025-2026 356C LLC
// SPDX-License-Identifier: GPL-3.0-or-later

#include "mock_http_file_server.h"

#ifdef HELIX_ENABLE_MOCKS

#include "hv/HttpServer.h"
#include "hv/base64.h"

#include <spdlog/spdlog.h>

#include <algorithm>
#include <arpa/inet.h>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <netinet/in.h>
#include <optional>
#include <string>
#include <sys/socket.h>
#include <unistd.h>
#include <vector>

namespace helix {

namespace {

/// Real PNG bytes rather than a synthesised image: the decoder under test is
/// stb_image, and the thing worth exercising is production-shaped input
/// (interlacing, palette, alpha), not the smallest buffer that parses.
const char* THUMBNAIL_ASSET = "assets/images/benchy_thumbnail_white.png";

std::vector<uint8_t> read_asset(const std::string& relative) {
    // CWD-relative, the same convention the rest of the tree uses for assets
    // (lv_image_set_src("A:assets/...")). --test is always launched from a
    // tree that has them.
    std::ifstream f(relative, std::ios::binary);
    if (!f) {
        return {};
    }
    return std::vector<uint8_t>((std::istreambuf_iterator<char>(f)),
                                std::istreambuf_iterator<char>());
}

/// Wrap PNG bytes in the slicer thumbnail block gcode_parser.cpp parses:
///   "; thumbnail begin WxH SIZE" / "; <base64>" ... / "; thumbnail end"
std::string make_gcode_header(const std::vector<uint8_t>& png) {
    std::string b64 = hv::Base64Encode(png.data(), static_cast<unsigned int>(png.size()));

    std::string out;
    out.reserve(b64.size() + 512);
    out += "; generated by HelixScreen MockHttpFileServer\n";
    out += "; thumbnail begin 300x300 " + std::to_string(png.size()) + "\n";
    // Slicers hard-wrap the base64 payload; match that so the extractor's
    // line-oriented accumulation is exercised rather than bypassed.
    constexpr size_t WRAP = 78;
    for (size_t i = 0; i < b64.size(); i += WRAP) {
        out += "; " + b64.substr(i, WRAP) + "\n";
    }
    out += "; thumbnail end\n";
    out += ";FLAVOR:Marlin\n;Generated with MockHttpFileServer\nG28\n";
    return out;
}

/// HELIX_MOCK_RANGE_IGNORE=1 - drop the Range header from every request so
/// libhv answers 200 with the whole body instead of slicing a 206: the
/// behaviour of server forks that never implemented byte ranges.
static bool range_ignore_enabled() {
    static const bool enabled = [] {
        const char* v = std::getenv("HELIX_MOCK_RANGE_IGNORE");
        return v && v[0] && std::string(v) != "0";
    }();
    return enabled;
}

/// Strictly parse the unsigned decimal spanning s[from, to). An empty span or
/// any non-digit is malformed: "bytes=abc-def" must be ignored as a whole, not
/// clamped to a 1-byte 206 at offset 0.
std::optional<size_t> parse_range_num(const std::string& s, size_t from, size_t to) {
    if (from >= to) {
        return std::nullopt;
    }
    size_t v = 0;
    for (size_t i = from; i < to; i++) {
        if (s[i] < '0' || s[i] > '9') {
            return std::nullopt;
        }
        v = v * 10 + static_cast<size_t>(s[i] - '0');
    }
    return v;
}

/// Slice a body per a "bytes=a-b" / "bytes=-n" Range header and mark the
/// response 206, the way a range-supporting Moonraker answers. libhv does not
/// do this for a handler-set body, so the server must honour the header
/// itself; HELIX_MOCK_RANGE_IGNORE skips this to emulate a server that never
/// implemented ranges (200, whole file). A malformed header (non-numeric
/// bounds, an inverted span) is ignored the same way - 200, whole body - while
/// valid syntax that selects no bytes ("bytes=-0", a start past the body)
/// answers 416 naming the full size in Content-Range.
void apply_range(HttpRequest* req, HttpResponse* resp) {
    std::string range = req->GetHeader("Range");
    if (range.rfind("bytes=", 0) != 0 || resp->body.empty()) {
        return;
    }
    const size_t size = resp->body.size();
    size_t dash = range.find('-', 6);
    if (dash == std::string::npos) {
        return;
    }

    auto unsatisfiable = [&] {
        resp->status_code = HTTP_STATUS_RANGE_NOT_SATISFIABLE;
        resp->SetHeader("Content-Range", "bytes */" + std::to_string(size));
        resp->body.clear();
    };

    size_t start = 0;
    size_t end = 0;
    if (dash == 6) { // suffix form: the last N bytes
        auto n = parse_range_num(range, 7, range.size());
        if (!n) {
            return;
        }
        if (*n == 0) {
            unsatisfiable();
            return;
        }
        const size_t take = std::min(*n, size);
        start = size - take;
        end = size - 1;
    } else {
        auto first = parse_range_num(range, 6, dash);
        const bool last_explicit = dash + 1 < range.size();
        auto last = last_explicit ? parse_range_num(range, dash + 1, range.size())
                                  : std::optional<size_t>(size - 1);
        if (!first || !last) {
            return;
        }
        // Only an explicitly inverted span is invalid syntax; an open-ended
        // range has no end to invert, and a start past the body is valid
        // syntax that selects nothing.
        if (last_explicit && *first > *last) {
            return;
        }
        if (*first >= size) {
            unsatisfiable();
            return;
        }
        start = *first;
        end = std::min(*last, size - 1);
    }

    resp->status_code = HTTP_STATUS_PARTIAL_CONTENT;
    resp->SetHeader("Content-Range", "bytes " + std::to_string(start) + "-" + std::to_string(end) +
                                         "/" + std::to_string(size));
    resp->body = resp->body.substr(start, end - start + 1);
}

bool ends_with(const std::string& s, const std::string& suffix) {
    return s.size() >= suffix.size() &&
           s.compare(s.size() - suffix.size(), suffix.size(), suffix) == 0;
}

/// Bind a loopback listener on an ephemeral port and report which one.
///
/// libhv's http_server_run() skips binding entirely when `port == 0` (it guards
/// on `port > 0`), so asking it for an ephemeral port yields a server that
/// never listens. It does honour a pre-bound descriptor via setListenFD(), and
/// handing it one is also race-free — picking a port, closing, and re-binding
/// would leave a window for another process to take it.
int bind_loopback_ephemeral(int* out_port) {
    int fd = ::socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0) {
        return -1;
    }
    int reuse = 1;
    ::setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse));

    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    addr.sin_port = 0;
    if (::bind(fd, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) != 0 ||
        ::listen(fd, 16) != 0) {
        ::close(fd);
        return -1;
    }

    sockaddr_in bound{};
    socklen_t len = sizeof(bound);
    if (::getsockname(fd, reinterpret_cast<sockaddr*>(&bound), &len) != 0) {
        ::close(fd);
        return -1;
    }
    *out_port = ntohs(bound.sin_port);
    return fd;
}

} // namespace

struct MockHttpFileServer::Impl {
    hv::HttpService router;
    hv::HttpServer server;
    std::vector<uint8_t> png;
    std::string gcode_header;
};

MockHttpFileServer::MockHttpFileServer() : impl_(std::make_unique<Impl>()) {}

MockHttpFileServer::~MockHttpFileServer() {
    stop();
}

bool MockHttpFileServer::start() {
    if (running_) {
        return true;
    }

    impl_->png = read_asset(THUMBNAIL_ASSET);
    if (impl_->png.empty()) {
        spdlog::warn("[MockHttpFileServer] Could not read {} — thumbnail mocking disabled",
                     THUMBNAIL_ASSET);
        return false;
    }
    impl_->gcode_header = make_gcode_header(impl_->png);

    // Moonraker serves everything under the gcodes root from one prefix. The
    // extension decides what we hand back, which keeps this indifferent to
    // whatever filenames the mock client invents.
    const std::vector<uint8_t>& png = impl_->png;
    const std::string& gcode = impl_->gcode_header;
    impl_->router.GET(
        "/server/files/gcodes/*", [&png, &gcode](HttpRequest* req, HttpResponse* resp) {
            if (range_ignore_enabled()) {
                req->headers.erase("Range");
            }
            const std::string& path = req->path;
            if (ends_with(path, ".png")) {
                resp->content_type = APPLICATION_OCTET_STREAM;
                resp->body.assign(reinterpret_cast<const char*>(png.data()), png.size());
                apply_range(req, resp);
                spdlog::debug("[MockHttpFileServer] {} {} ({} bytes, png)",
                              static_cast<int>(resp->status_code), path, resp->body.size());
                return static_cast<int>(resp->status_code);
            }
            if (ends_with(path, ".gcode")) {
                // HELIX_MOCK_GCODE_SERVE=<path> - serve a real file's bytes (any
                // size) instead of the tiny synthesised header. Reproduces the
                // big-file flows end to end: the whole-file preview download and
                // the byte-range reads the tail/footer scanners issue. libhv
                // slices the Range out of the body either way.
                static const std::string serve_file = [] {
                    const char* v = std::getenv("HELIX_MOCK_GCODE_SERVE");
                    return v ? std::string(v) : std::string();
                }();
                if (!serve_file.empty()) {
                    std::ifstream f(serve_file, std::ios::binary);
                    if (f) {
                        resp->content_type = TEXT_PLAIN;
                        resp->body.assign((std::istreambuf_iterator<char>(f)),
                                          std::istreambuf_iterator<char>());
                        apply_range(req, resp);
                        spdlog::debug("[MockHttpFileServer] {} {} ({} bytes, from {})",
                                      static_cast<int>(resp->status_code), path, resp->body.size(),
                                      serve_file);
                        return static_cast<int>(resp->status_code);
                    }
                    spdlog::warn("[MockHttpFileServer] HELIX_MOCK_GCODE_SERVE file unreadable: {}",
                                 serve_file);
                }
                // A synthesized header shorter than a requested range slices to
                // whatever exists, the same way a real short gcode file answers.
                resp->content_type = TEXT_PLAIN;
                resp->body = gcode;
                apply_range(req, resp);
                spdlog::debug("[MockHttpFileServer] {} {} ({} bytes, gcode header)",
                              static_cast<int>(resp->status_code), path, resp->body.size());
                return static_cast<int>(resp->status_code);
            }
            spdlog::debug("[MockHttpFileServer] 404 {}", path);
            return 404;
        });

    int port = 0;
    int fd = bind_loopback_ephemeral(&port);
    if (fd < 0) {
        spdlog::warn("[MockHttpFileServer] Could not bind a loopback port — "
                     "thumbnail mocking disabled");
        return false;
    }

    impl_->server.registerHttpService(&impl_->router);
    impl_->server.setListenFD(fd);
    impl_->server.setPort(0); // leave libhv's own Listen() path disabled
    impl_->server.setThreadNum(1);

    if (impl_->server.start() != 0) {
        spdlog::warn("[MockHttpFileServer] Server failed to start on port {}", port);
        ::close(fd);
        return false;
    }

    base_url_ = "http://127.0.0.1:" + std::to_string(port);
    running_ = true;
    spdlog::info("[MockHttpFileServer] Serving mock Moonraker files at {}", base_url_);
    return true;
}

void MockHttpFileServer::stop() {
    if (!running_) {
        return;
    }
    impl_->server.stop();
    running_ = false;
    base_url_.clear();
    spdlog::debug("[MockHttpFileServer] Stopped");
}

} // namespace helix

#endif // HELIX_ENABLE_MOCKS
