// Copyright (C) 2025-2026 356C LLC
// SPDX-License-Identifier: GPL-3.0-or-later

#include "mock_http_file_server.h"

#ifdef HELIX_ENABLE_MOCKS

#include "hv/HttpServer.h"
#include "hv/base64.h"

#include <spdlog/spdlog.h>

#include <arpa/inet.h>
#include <cstring>
#include <fstream>
#include <netinet/in.h>
#include <string>
#include <sys/socket.h>
#include <unistd.h>
#include <vector>

namespace helix {

namespace {

/// Real PNG bytes rather than a synthesised image: the decoder under test is
/// stb_image, and the thing worth exercising is production-shaped input
/// (interlacing, palette, alpha), not the smallest buffer that parses.
const char* THUMBNAIL_ASSET = "assets/images/benchy_thumbnail_white.png";

std::vector<uint8_t> read_asset(const std::string& relative) {
    // CWD-relative, the same convention the rest of the tree uses for assets
    // (lv_image_set_src("A:assets/...")). --test is always launched from a
    // tree that has them.
    std::ifstream f(relative, std::ios::binary);
    if (!f) {
        return {};
    }
    return std::vector<uint8_t>((std::istreambuf_iterator<char>(f)),
                                std::istreambuf_iterator<char>());
}

/// Wrap PNG bytes in the slicer thumbnail block gcode_parser.cpp parses:
///   "; thumbnail begin WxH SIZE" / "; <base64>" ... / "; thumbnail end"
std::string make_gcode_header(const std::vector<uint8_t>& png) {
    std::string b64 = hv::Base64Encode(png.data(), static_cast<unsigned int>(png.size()));

    std::string out;
    out.reserve(b64.size() + 512);
    out += "; generated by HelixScreen MockHttpFileServer\n";
    out += "; thumbnail begin 300x300 " + std::to_string(png.size()) + "\n";
    // Slicers hard-wrap the base64 payload; match that so the extractor's
    // line-oriented accumulation is exercised rather than bypassed.
    constexpr size_t WRAP = 78;
    for (size_t i = 0; i < b64.size(); i += WRAP) {
        out += "; " + b64.substr(i, WRAP) + "\n";
    }
    out += "; thumbnail end\n";
    out += ";FLAVOR:Marlin\n;Generated with MockHttpFileServer\nG28\n";
    return out;
}

bool ends_with(const std::string& s, const std::string& suffix) {
    return s.size() >= suffix.size() &&
           s.compare(s.size() - suffix.size(), suffix.size(), suffix) == 0;
}

/// Bind a loopback listener on an ephemeral port and report which one.
///
/// libhv's http_server_run() skips binding entirely when `port == 0` (it guards
/// on `port > 0`), so asking it for an ephemeral port yields a server that
/// never listens. It does honour a pre-bound descriptor via setListenFD(), and
/// handing it one is also race-free — picking a port, closing, and re-binding
/// would leave a window for another process to take it.
int bind_loopback_ephemeral(int* out_port) {
    int fd = ::socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0) {
        return -1;
    }
    int reuse = 1;
    ::setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse));

    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    addr.sin_port = 0;
    if (::bind(fd, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) != 0 ||
        ::listen(fd, 16) != 0) {
        ::close(fd);
        return -1;
    }

    sockaddr_in bound{};
    socklen_t len = sizeof(bound);
    if (::getsockname(fd, reinterpret_cast<sockaddr*>(&bound), &len) != 0) {
        ::close(fd);
        return -1;
    }
    *out_port = ntohs(bound.sin_port);
    return fd;
}

} // namespace

struct MockHttpFileServer::Impl {
    hv::HttpService router;
    hv::HttpServer server;
    std::vector<uint8_t> png;
    std::string gcode_header;
};

MockHttpFileServer::MockHttpFileServer() : impl_(std::make_unique<Impl>()) {}

MockHttpFileServer::~MockHttpFileServer() {
    stop();
}

bool MockHttpFileServer::start() {
    if (running_) {
        return true;
    }

    impl_->png = read_asset(THUMBNAIL_ASSET);
    if (impl_->png.empty()) {
        spdlog::warn("[MockHttpFileServer] Could not read {} — thumbnail mocking disabled",
                     THUMBNAIL_ASSET);
        return false;
    }
    impl_->gcode_header = make_gcode_header(impl_->png);

    // Moonraker serves everything under the gcodes root from one prefix. The
    // extension decides what we hand back, which keeps this indifferent to
    // whatever filenames the mock client invents.
    const std::vector<uint8_t>& png = impl_->png;
    const std::string& gcode = impl_->gcode_header;
    impl_->router.GET(
        "/server/files/gcodes/*", [&png, &gcode](HttpRequest* req, HttpResponse* resp) {
            const std::string& path = req->path;
            if (ends_with(path, ".png")) {
                resp->content_type = APPLICATION_OCTET_STREAM;
                resp->body.assign(reinterpret_cast<const char*>(png.data()), png.size());
                spdlog::debug("[MockHttpFileServer] 200 {} ({} bytes, png)", path, png.size());
                return 200;
            }
            if (ends_with(path, ".gcode")) {
                // download_file_partial() asks for a byte range; libhv answers the
                // Range itself when the body is set, and a caller that asked for
                // the first 100 KB of a shorter body simply gets the whole thing —
                // which is what a real short gcode file does too.
                resp->content_type = TEXT_PLAIN;
                resp->body = gcode;
                spdlog::debug("[MockHttpFileServer] 200 {} ({} bytes, gcode header)", path,
                              gcode.size());
                return 200;
            }
            spdlog::debug("[MockHttpFileServer] 404 {}", path);
            return 404;
        });

    int port = 0;
    int fd = bind_loopback_ephemeral(&port);
    if (fd < 0) {
        spdlog::warn("[MockHttpFileServer] Could not bind a loopback port — "
                     "thumbnail mocking disabled");
        return false;
    }

    impl_->server.registerHttpService(&impl_->router);
    impl_->server.setListenFD(fd);
    impl_->server.setPort(0); // leave libhv's own Listen() path disabled
    impl_->server.setThreadNum(1);

    if (impl_->server.start() != 0) {
        spdlog::warn("[MockHttpFileServer] Server failed to start on port {}", port);
        ::close(fd);
        return false;
    }

    base_url_ = "http://127.0.0.1:" + std::to_string(port);
    running_ = true;
    spdlog::info("[MockHttpFileServer] Serving mock Moonraker files at {}", base_url_);
    return true;
}

void MockHttpFileServer::stop() {
    if (!running_) {
        return;
    }
    impl_->server.stop();
    running_ = false;
    base_url_.clear();
    spdlog::debug("[MockHttpFileServer] Stopped");
}

} // namespace helix

#endif // HELIX_ENABLE_MOCKS
