#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Bundle HelixScreen uninstaller into a single file
# Mirrors the approach used by bundle-installer.sh for install.sh
#
# Usage:
#   ./bundle-uninstaller.sh > uninstall.sh
#   ./bundle-uninstaller.sh -o uninstall.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LIB_DIR="$SCRIPT_DIR/lib/installer"
OUTPUT_FILE=""

# Parse arguments
while [ $# -gt 0 ]; do
    case "$1" in
        -o|--output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: $0 [-o output_file]"
            echo ""
            echo "Bundles the modular uninstaller into a single file."
            echo "If no output file specified, writes to stdout."
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# Generate the bundled uninstaller
generate_bundle() {
    # Header
    cat << 'HEADER'
#!/bin/sh
# Copyright (C) 2025-2026 356C LLC
# SPDX-License-Identifier: GPL-3.0-or-later
#
# HelixScreen Uninstaller
# This file is auto-generated by bundle-uninstaller.sh
#
# Usage:
#   ./uninstall.sh              # Interactive uninstall
#   ./uninstall.sh --force      # Skip confirmation prompt
#   ./uninstall.sh --mod-payload [--payload-root DIR]
#                              # Also remove a payload-contract install (the
#                              # firmware mod's payload tree, display takeover
#                              # and update stanza)
#
# This script:
#   1. Stops HelixScreen
#   2. Removes init script or systemd service
#   3. Removes installation directory and caches
#   4. Re-enables previous UI (GuppyScreen, KlipperScreen, etc.)
#   5. Removes Moonraker update_manager section

# Fail fast on any error
set -e

# Configuration
GITHUB_REPO="prestonbrown/helixscreen"
SERVICE_NAME="helixscreen"

# Previous UIs we may need to re-enable (for scanning)
PREVIOUS_UIS="guppyscreen GuppyScreen featherscreen FeatherScreen klipperscreen KlipperScreen"

HEADER

    # Include each module (only those needed for uninstall).
    # service.sh provides stop_service, called by uninstall.sh's clean_old_installation.
    # camera.sh provides uninstall_camera_k2, called by uninstall.sh (K2 ustreamer teardown).
    # host_profile.sh provides the mod-ownership guard behind uninstall.sh's
    # HELIX_INSTALL_DIRS sweeps and moonraker.sh's stanza writer; main() below
    # probes it before set_install_paths' install-dir gate calls it.
    for module in common.sh host_profile.sh platform.sh permissions.sh requirements.sh forgex.sh service.sh moonraker.sh camera.sh uninstall.sh; do
        module_path="$LIB_DIR/$module"
        if [ ! -f "$module_path" ]; then
            echo "ERROR: Module not found: $module_path" >&2
            exit 1
        fi

        echo ""
        echo "# ============================================"
        echo "# Module: $module"
        echo "# ============================================"
        echo ""

        # Skip shebang, SPDX header, and source guard lines
        # Keep everything else
        awk '
            # Skip shebang
            /^#!/ { next }
            # Skip SPDX header
            /^# SPDX-License-Identifier:/ { next }
            # Skip module comment block at top (first few lines starting with #)
            NR <= 10 && /^# / { next }
            # Skip source guard
            /^\[ -n "\${_HELIX_.*_SOURCED:-}"/ { next }
            /_HELIX_.*_SOURCED=1/ { next }
            # Skip empty lines at the start
            NR <= 15 && /^$/ { next }
            # Print everything else
            { print }
        ' "$module_path"
    done

    # Include the main orchestration code
    cat << 'MAIN'

# ============================================
# Main orchestration
# ============================================

# Re-enable previous UI (extended version with scanning)
reenable_previous_ui() {
    log_info "Looking for previous screen UI to re-enable..."

    found_ui=false
    restored_xorg=false

    # Platform-specific restores live in uninstall.sh's restore_previous_ui_platform()
    # and cover what the generic scanning below cannot: COSMOS sibling UIs, the
    # Snapmaker U1 stock binary + /oem/.debug, AD5M zmod, and the Creality `app`
    # launcher. They were reachable only through uninstall(), which install.sh calls
    # but THIS bundle does not — its main() calls this function instead. So the
    # uninstaller users actually run silently restored nothing on those platforms.
    # Run it FIRST; the scanning below is the fallback for platforms it does not know.
    if type restore_previous_ui_platform >/dev/null 2>&1; then
        restore_previous_ui_platform "$platform"
        if [ -n "$HELIX_RESTORED_UI" ]; then
            log_success "Re-enabled: $HELIX_RESTORED_UI"
            found_ui=true
        fi
        [ -n "$HELIX_RESTORED_XORG" ] && restored_xorg=true
    fi

    # For ForgeX firmware, do comprehensive cleanup and restore
    if [ "$AD5M_FIRMWARE" = "forge_x" ]; then
        uninstall_forgex

        if [ -n "$restored_ui" ]; then
            found_ui=true
        fi
    fi

    # For K1/Simple AF, check for GuppyScreen
    if [ "$platform" = "k1" ]; then
        for k1_ui in /etc/init.d/S99guppyscreen /etc/init.d/S50guppyscreen; do
            if [ -f "$k1_ui" ]; then
                log_info "Re-enabling GuppyScreen for K1..."
                $SUDO chmod +x "$k1_ui" 2>/dev/null || true
                if "$k1_ui" start 2>/dev/null; then
                    log_success "Re-enabled and started: $k1_ui"
                    found_ui=true
                    break
                fi
            fi
        done
    fi

    # For Klipper Mod, re-enable Xorg first (required for KlipperScreen)
    if [ "$AD5M_FIRMWARE" = "klipper_mod" ] || [ -f "/etc/init.d/S40xorg" ]; then
        if [ -f "/etc/init.d/S40xorg" ]; then
            log_info "Re-enabling Xorg display server..."
            $SUDO chmod +x "/etc/init.d/S40xorg" 2>/dev/null || true
            restored_xorg=true
        fi
    fi

    # Try the specific previous UI script for this firmware
    if [ -n "$PREVIOUS_UI_SCRIPT" ] && [ -f "$PREVIOUS_UI_SCRIPT" ]; then
        log_info "Found previous UI: $PREVIOUS_UI_SCRIPT"
        $SUDO chmod +x "$PREVIOUS_UI_SCRIPT" 2>/dev/null || true
        if "$PREVIOUS_UI_SCRIPT" start 2>/dev/null; then
            log_success "Re-enabled and started: $PREVIOUS_UI_SCRIPT"
            found_ui=true
        else
            log_warn "Re-enabled but failed to start: $PREVIOUS_UI_SCRIPT"
            log_warn "You may need to reboot"
            found_ui=true
        fi
    fi

    # Scan for other UIs we might have disabled
    for ui in $PREVIOUS_UIS; do
        for initscript in /etc/init.d/S*${ui}* /opt/config/mod/.root/S*${ui}*; do
            [ "$initscript" = "$PREVIOUS_UI_SCRIPT" ] && continue
            if [ -f "$initscript" ] 2>/dev/null; then
                log_info "Found previous UI: $initscript"
                $SUDO chmod +x "$initscript" 2>/dev/null || true
                if [ "$found_ui" = false ]; then
                    if "$initscript" start 2>/dev/null; then
                        log_success "Re-enabled and started: $initscript"
                        found_ui=true
                    else
                        log_warn "Re-enabled but failed to start: $initscript"
                        log_warn "You may need to reboot"
                        found_ui=true
                    fi
                else
                    log_info "Re-enabled: $initscript (not started, another UI already running)"
                fi
            fi
        done

        if [ "$INIT_SYSTEM" = "systemd" ]; then
            if systemctl list-unit-files "${ui}.service" >/dev/null 2>&1; then
                log_info "Found previous UI (systemd): $ui"
                $SUDO systemctl enable "$ui" 2>/dev/null || true
                if $SUDO systemctl start "$ui" 2>/dev/null; then
                    log_success "Re-enabled and started: $ui"
                    found_ui=true
                else
                    log_warn "Re-enabled but failed to start: $ui"
                    found_ui=true
                fi
            fi
        fi
    done

    # Re-enable tslib for ForgeX (if not already handled by uninstall_forgex)
    if [ -f "/opt/config/mod/.root/S35tslib" ]; then
        $SUDO chmod +x "/opt/config/mod/.root/S35tslib" 2>/dev/null || true
    fi

    if [ "$found_ui" = false ]; then
        log_info "No previous screen UI found to re-enable"
        log_info "If you had a stock UI, a reboot may restore it"
    fi

    if [ "$restored_xorg" = true ]; then
        log_info "Re-enabled: Xorg (/etc/init.d/S40xorg)"
    fi
}

# Stop HelixScreen processes and service
stop_helixscreen() {
    log_info "Stopping HelixScreen..."

    # Stop via init system
    if [ "$INIT_SYSTEM" = "systemd" ]; then
        $SUDO systemctl stop helixscreen 2>/dev/null || true
        $SUDO systemctl disable helixscreen 2>/dev/null || true
    fi

    # Stop via configured init script
    if [ -n "$INIT_SCRIPT_DEST" ] && [ -x "$INIT_SCRIPT_DEST" ]; then
        $SUDO "$INIT_SCRIPT_DEST" stop 2>/dev/null || true
    fi

    # Also check all possible init script locations
    for init_script in $HELIX_INIT_SCRIPTS; do
        if [ -x "$init_script" ]; then
            $SUDO "$init_script" stop 2>/dev/null || true
        fi
    done

    # Kill any remaining processes (watchdog first to prevent crash dialog flash)
    # shellcheck disable=SC2086
    kill_process_by_name $HELIX_PROCESSES || true

    log_success "HelixScreen stopped"
}

# Remove init script or systemd service
remove_service() {
    log_info "Removing service configuration..."

    if [ "$INIT_SYSTEM" = "systemd" ]; then
        if [ -f "/etc/systemd/system/helixscreen.service" ]; then
            $SUDO rm -f "/etc/systemd/system/helixscreen.service"
            $SUDO systemctl daemon-reload
            log_success "Removed systemd service"
        fi
    fi

    # Remove configured init script
    if [ -n "$INIT_SCRIPT_DEST" ] && [ -f "$INIT_SCRIPT_DEST" ]; then
        $SUDO rm -f "$INIT_SCRIPT_DEST"
        log_success "Removed SysV init script: $INIT_SCRIPT_DEST"
    fi

    # Also check and remove from all possible locations
    for init_script in $HELIX_INIT_SCRIPTS; do
        if [ -f "$init_script" ]; then
            $SUDO rm -f "$init_script"
            log_success "Removed SysV init script: $init_script"
        fi
    done
}

# Remove installation directory
remove_installation() {
    log_info "Removing installation..."

    removed_any=false

    # Re-enable services from state file BEFORE removing install dir
    reenable_disabled_services

    # Remove from configured location
    if [ -d "$INSTALL_DIR" ]; then
        # The configured install is refused wholesale when the mod owns it —
        # that path is the mod's payload root, and the standalone uninstaller
        # has no business deleting it (same rule as install.sh's entry gate).
        host_refuse_mod_owned "uninstall of" "$INSTALL_DIR"
        $SUDO rm -rf "$INSTALL_DIR"
        log_success "Removed $INSTALL_DIR"
        removed_any=true
        # Also remove updater repo clone if present
        if [ -d "${INSTALL_DIR}-repo" ]; then
            $SUDO rm -rf "${INSTALL_DIR}-repo"
            log_success "Removed ${INSTALL_DIR}-repo"
        fi
    fi

    # Also check and remove from all possible locations
    for install_dir in $HELIX_INSTALL_DIRS; do
        if [ -d "$install_dir" ] && [ "$install_dir" != "$INSTALL_DIR" ]; then
            # Sweep entries the mod owns are skipped, not removed — same rule
            # as uninstall.sh's own sweeps.
            if host_mod_destruct_blocked "$install_dir"; then
                log_warn "Skipping mod-owned $install_dir (managed by the firmware mod)"
                continue
            fi
            $SUDO rm -rf "$install_dir"
            log_success "Removed $install_dir"
            removed_any=true
            if [ -d "${install_dir}-repo" ]; then
                $SUDO rm -rf "${install_dir}-repo"
                log_success "Removed ${install_dir}-repo"
            fi
        fi
    done

    if [ "$removed_any" = false ]; then
        log_warn "No HelixScreen installation found (already removed?)"
    fi

    # Clean up PID files, log file, and active flag
    $SUDO rm -f /var/run/helixscreen.pid 2>/dev/null || true
    $SUDO rm -f /var/run/helix-splash.pid 2>/dev/null || true
    $SUDO rm -f /tmp/helixscreen.log 2>/dev/null || true
    $SUDO rm -f /tmp/helixscreen_active 2>/dev/null || true

    # Clean up cache directories
    for cache_dir in /root/.cache/helix /tmp/helix_thumbs /.cache/helix; do
        if [ -d "$cache_dir" ] 2>/dev/null; then
            log_info "Removing cache: $cache_dir"
            $SUDO rm -rf "$cache_dir"
        fi
    done

    # Clean up macOS resource fork files (created by scp from Mac)
    for pattern in /opt/._helixscreen /root/._helixscreen; do
        $SUDO rm -f "$pattern" 2>/dev/null || true
    done

    # Sweep state dirs holding rolling config backups (out-of-INSTALL_DIR by design).
    # Defined in lib/installer/common.sh; bundled into this script.
    clean_helix_state_dirs
}

# Refuse to run if $0 lives inside $INSTALL_DIR — we're about to delete
# that directory and would yank the script out from under ourselves mid-run.
# Tell the user how to re-invoke from /tmp.  Called from main() after
# set_install_paths so $INSTALL_DIR is populated.  Normalizes a trailing
# slash so an INSTALL_DIR override like "/opt/helixscreen/" still matches.
guard_self_delete() {
    [ -n "${INSTALL_DIR:-}" ] || return 0

    local _script_dir _script_abs _install_norm
    _script_dir="$(cd "$(dirname "$0")" 2>/dev/null && pwd)" || return 0
    _script_abs="${_script_dir}/$(basename "$0")"
    _install_norm="${INSTALL_DIR%/}"

    case "$_script_abs" in
        "$_install_norm"/*|"$_install_norm")
            log_error "Refusing to run: uninstall script is inside \$INSTALL_DIR"
            log_error "  script:      $_script_abs"
            log_error "  INSTALL_DIR: $INSTALL_DIR"
            log_error ""
            log_error "This script is about to delete its own directory.  Copy it"
            log_error "out first, then re-run from the copy:"
            log_error "  cp '$_script_abs' /tmp/uninstall.sh"
            log_error "  sh /tmp/uninstall.sh $*"
            exit 1
            ;;
    esac
}

# Main uninstall
main() {
    force=false

    # Parse arguments
    while [ $# -gt 0 ]; do
        case "$1" in
            --force|-f)
                force=true
                shift
                ;;
            --mod-payload)
                # Arm the payload uninstall: the only run permitted to remove
                # the firmware mod's payload tree (the same destruct exemption
                # install.sh's payload contract arms). Uninstall deliberately
                # does not auto-detect this the way install does — removing a
                # mod-owned subtree must be an explicit opt-in.
                HELIX_MOD_PAYLOAD=1
                shift
                ;;
            --payload-root)
                # Where this run's payload uninstall points — the same flag
                # the installer takes. Names the root ONLY: the removal itself
                # still needs --mod-payload (an inert flag warns below).
                if [ -z "${2:-}" ]; then
                    log_error "--payload-root requires a path argument"
                    exit 1
                fi
                MOD_PAYLOAD_ROOT="$2"
                shift 2
                ;;
            --help|-h)
                echo "HelixScreen Uninstaller"
                echo ""
                echo "Usage: $0 [options]"
                echo ""
                echo "Options:"
                echo "  --force, -f   Skip confirmation prompt"
                echo "  --mod-payload Also remove a payload-contract install (the"
                echo "                firmware mod's payload tree, display takeover"
                echo "                and update stanza)"
                echo "  --payload-root DIR"
                echo "                The payload root to remove (default: the root"
                echo "                the install recorded, else the probed default)"
                echo "                Requires --mod-payload to do anything"
                echo "  --help, -h    Show this help message"
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                exit 1
                ;;
        esac
    done

    echo ""
    echo "${CYAN}========================================${NC}"
    echo "${CYAN}     HelixScreen Uninstaller${NC}"
    echo "${CYAN}========================================${NC}"
    echo ""

    # Probe the host before set_install_paths' install-dir gate runs —
    # its mod-ownership guard needs HOST_MOD_ROOT already probed.
    host_profile_probe

    # Detect platform and firmware to set correct paths
    platform=$(detect_platform)
    if [ "$platform" = "ad5x" ]; then
        ad5x_check_chroot_context
    fi
    # The FlashForge mods ship for both Adventurer platforms, so ad5x runs the
    # same unified flavor detector ad5m always has (main.sh does the same): a
    # Forge-X AD5X must light the forge_x branches below — the payload arm's
    # display restore included — instead of leaving AD5M_FIRMWARE empty.
    if [ "$platform" = "ad5m" ] || [ "$platform" = "ad5x" ]; then
        AD5M_FIRMWARE=$(detect_mod_flavor)
        log_info "Detected mod flavor: $AD5M_FIRMWARE"
    fi
    set_install_paths "$platform" "$AD5M_FIRMWARE"

    # Refuse to self-delete (must be after set_install_paths)
    guard_self_delete "$@"

    # Check for root
    check_permissions "$platform"

    # Detect init system
    detect_init_system

    # Confirm unless --force
    if [ "$force" = false ]; then
        echo "This will:"
        echo "  - Stop HelixScreen"
        echo "  - Remove $INSTALL_DIR"
        echo "  - Remove service configuration"
        echo "  - Remove rolling config backups (/var/lib/helixscreen + .helixscreen under the service user's home)"
        echo "  - Re-enable previous screen UI (if found)"
        if [ "$AD5M_FIRMWARE" = "forge_x" ]; then
            echo "  - Restore ForgeX display configuration (the mode recorded at install)"
        fi
        if [ "${HELIX_MOD_PAYLOAD:-}" = "1" ]; then
            echo "  - Remove the payload install at $INSTALL_DIR (mod-owned)"
        fi
        echo ""
        printf "Are you sure you want to continue? [y/N] "
        read -r response
        case "$response" in
            [yY][eE][sS]|[yY])
                ;;
            *)
                log_info "Uninstall cancelled"
                exit 0
                ;;
        esac
        echo ""
    fi

    # Perform uninstall.  Order matters:
    #   1. Drop .uninstalling sentinel so helixscreen-update.service refuses
    #      to fire while we're working.  Trap on EXIT/INT/TERM covers an
    #      aborted run so a stuck sentinel doesn't silently block all future
    #      update.service firings.
    #   2. Edit moonraker.conf FIRST.  If anything races us (auto-refresh,
    #      a user clicking Update in Mainsail), having the section gone
    #      before we start dismantling files is the on-disk defense; the
    #      systemd path-unit defense (sentinel) covers the in-process side.
    #   3. Stop, remove, sweep — sweep also clears the sentinel via
    #      clean_helix_state_dirs.
    # A --payload-root without the arm names a root nothing will touch — say
    # so instead of letting the operator believe it directed the removal.
    if [ -n "${MOD_PAYLOAD_ROOT:-}" ] && [ "${HELIX_MOD_PAYLOAD:-}" != "1" ]; then
        log_warn "--payload-root ignored without --mod-payload: it names where"
        log_warn "the armed payload uninstall removes, and this run is not armed."
    fi

    trap '_sweep_uninstalling_sentinel' EXIT INT TERM
    _drop_uninstalling_sentinel
    remove_update_manager_section || true
    stop_helixscreen
    remove_service
    # The payload arm runs before the generic sweeps: it restores the mod's
    # display mode while the payload is still in place, then removes the
    # mod-owned payload root the sweeps below would otherwise skip (or refuse).
    if [ "${HELIX_MOD_PAYLOAD:-}" = "1" ]; then
        uninstall_mod_payload
    fi
    remove_installation
    reenable_previous_ui

    echo ""
    echo "${GREEN}========================================${NC}"
    echo "${GREEN}    Uninstall Complete!${NC}"
    echo "${GREEN}========================================${NC}"
    echo ""
    log_info "HelixScreen has been removed."
    log_info "A reboot is recommended to ensure clean state."
    echo ""
}

# Only run when executed directly (not when sourced for testing)
case "${0##*/}" in
    uninstall.sh) main "$@" ;;
esac
MAIN
}

# Output to file or stdout
if [ -n "$OUTPUT_FILE" ]; then
    generate_bundle > "$OUTPUT_FILE"
    chmod +x "$OUTPUT_FILE"
    echo "Generated: $OUTPUT_FILE"
    echo "Size: $(wc -c < "$OUTPUT_FILE" | tr -d ' ') bytes"
else
    generate_bundle
fi
