#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Bundle HelixScreen installer into a single file for curl|sh usage
#
# Usage:
#   ./bundle-installer.sh > install.sh
#   ./bundle-installer.sh -o install.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LIB_DIR="$SCRIPT_DIR/lib/installer"
OUTPUT_FILE=""

# Parse arguments
while [ $# -gt 0 ]; do
    case "$1" in
        -o|--output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: $0 [-o output_file]"
            echo ""
            echo "Bundles the modular installer into a single file."
            echo "If no output file specified, writes to stdout."
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# Generate the bundled installer
generate_bundle() {
    # Header
    cat << 'HEADER'
#!/bin/sh
# Copyright (C) 2025-2026 356C LLC
# SPDX-License-Identifier: GPL-3.0-or-later
#
# !! AUTO-GENERATED — DO NOT EDIT !!
# Generated by: scripts/bundle-installer.sh
# Edit the modular sources in scripts/lib/installer/ instead.
#
# HelixScreen Installer
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/prestonbrown/helixscreen/main/scripts/install.sh | sh
#
# Or download and run:
#   wget https://raw.githubusercontent.com/prestonbrown/helixscreen/main/scripts/install.sh
#   chmod +x install.sh
#   ./install.sh
#
# Options:
#   --update    Update existing installation (preserves config)
#   --uninstall Remove HelixScreen
#   --clean     Remove old installation completely before installing (no config backup)
#   --version   Specify version (default: latest)
#

# Mark as bundled installer (modules check this to skip sourcing)
_HELIX_BUNDLED_INSTALLER=1

# Fail fast on any error
set -eu

# Harden PATH against third-party mods that prepend command-shim directories onto
# the login-shell PATH (e.g. Entware's /opt/bin, or k2-improvements' /mnt/UDISK/bin
# wrappers for sudo/systemctl/supervisorctl injected via /etc/profile.d). Putting
# the stock system directories first keeps our pidof/killall/kill/etc. resolving to
# the real binaries during install. Appended (not replaced) so any genuinely needed
# non-standard tool still resolves as a fallback.
export PATH="/usr/sbin:/usr/bin:/sbin:/bin:${PATH:-}"

# Configuration
GITHUB_REPO="prestonbrown/helixscreen"
SERVICE_NAME="helixscreen"

HEADER

    # Include each module (skip shebang and source guards).
    # Order matters: common.sh first (logging/colors), then host_profile.sh
    # (its guard calls log_error), uninstall.sh and main.sh last (they
    # reference functions defined elsewhere in this list).
    for module in common.sh host_profile.sh platform.sh permissions.sh requirements.sh forgex.sh competing_uis.sh printer_seed.sh klipper_include.sh release.sh service.sh audio.sh moonraker.sh camera.sh recovery.sh kiauh.sh uninstall.sh main.sh; do
        module_path="$LIB_DIR/$module"
        if [ ! -f "$module_path" ]; then
            echo "ERROR: Module not found: $module_path" >&2
            exit 1
        fi

        echo ""
        echo "# ============================================"
        echo "# Module: $module"
        echo "# ============================================"
        echo ""

        # Skip shebang, SPDX header, and source guard lines
        # Keep everything else
        awk '
            # Skip shebang (only the first line — not heredoc content)
            NR == 1 && /^#!/ { next }
            # Skip SPDX header
            /^# SPDX-License-Identifier:/ { next }
            # Skip module comment block at top (first few lines starting with #)
            NR <= 10 && /^# / { next }
            # Skip source guard
            /^\[ -n "\${_HELIX_.*_SOURCED:-}"/ { next }
            /_HELIX_.*_SOURCED=1/ { next }
            # Skip empty lines at the start
            NR <= 15 && /^$/ { next }
            # Print everything else
            { print }
        ' "$module_path"
    done

    # Append the main "$@" call so the bundled script actually runs.
    # All function definitions (including main itself) come from main.sh,
    # which is the last module in the loop above.
    cat << 'MAIN'

# Run main
main "$@"
MAIN
}

# Output to file or stdout
if [ -n "$OUTPUT_FILE" ]; then
    generate_bundle > "$OUTPUT_FILE"
    chmod +x "$OUTPUT_FILE"
    echo "Generated: $OUTPUT_FILE"
    echo "Size: $(wc -c < "$OUTPUT_FILE" | tr -d ' ') bytes"
else
    generate_bundle
fi
