#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Generate build/generated/contributors.h from CONTRIBUTORS.txt (preferred)
# or from git history as a fallback.
#
# CONTRIBUTORS.txt is the source of truth — committed to the repo so cross-
# compile Docker builds and shallow CI checkouts produce correct output.
# Regenerate it with `make update-contributors` (reads full git history with
# .mailmap applied).

set -euo pipefail

OUTDIR="${BUILD_DIR:-build}/generated"
OUTFILE="$OUTDIR/contributors.h"
TMPFILE="$(mktemp)"

trap 'rm -f "$TMPFILE"' EXIT

mkdir -p "$OUTDIR"

contributors=""

# Prefer the committed CONTRIBUTORS.txt — works in any build environment,
# no git required, no shallow-clone pitfalls.
if [ -f "CONTRIBUTORS.txt" ]; then
    contributors=$(grep -v '^[[:space:]]*\(#\|$\)' CONTRIBUTORS.txt | awk 'length >= 2' || true)
elif command -v git >/dev/null 2>&1 && git -c safe.directory='*' rev-parse --git-dir >/dev/null 2>&1; then
    # Fallback: derive from git history (respects .mailmap via %aN).
    contributors=$(git -c safe.directory='*' log --format='%aN' | sort -u \
        | grep -ivE 'bot\b|\[bot\]|dependabot|github-actions|claude' \
        | awk 'length >= 2' || true)
fi

# Generate the header into a temp file
{
    echo "// SPDX-License-Identifier: GPL-3.0-or-later"
    echo "// Auto-generated by gen-contributors.sh — do not edit"
    echo "#pragma once"
    echo ""
    echo "inline constexpr const char* CONTRIBUTORS[] = {"
    while IFS= read -r name; do
        [ -z "$name" ] && continue
        escaped=$(printf '%s' "$name" | sed 's/"/\\"/g')
        echo "    \"$escaped\","
    done <<< "$contributors"
    echo "};"
    echo ""
    echo "inline constexpr int CONTRIBUTOR_COUNT = sizeof(CONTRIBUTORS) / sizeof(CONTRIBUTORS[0]);"
} > "$TMPFILE"

# Only update if content changed
if [ -f "$OUTFILE" ] && diff -q "$TMPFILE" "$OUTFILE" >/dev/null 2>&1; then
    exit 0
fi

cp "$TMPFILE" "$OUTFILE"
echo "Generated $OUTFILE"
