#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Generate build/generated/helix_git_hash.h with the short commit hash.
#
# The hash lives in a generated header instead of a -D on the global compiler
# flags because it changes on every commit, and a per-commit macro on every
# translation unit's command line defeats ccache's direct mode for the entire
# project. Measured on CI: a run whose sha matched the restored cache got 86%
# direct hits and built in ~12 minutes; a run whose sha differed got 43.7% (the
# submodule share, since SUBMODULE_CFLAGS never carried the define) and took
# over two hours.
#
# Only src/system/helix_version.cpp includes this header, so a new commit
# rebuilds exactly one object instead of all ~750.

set -euo pipefail

OUTDIR="${BUILD_DIR:-build}/generated"
OUTFILE="$OUTDIR/helix_git_hash.h"
TMPFILE="$(mktemp)"

trap 'rm -f "$TMPFILE"' EXIT

mkdir -p "$OUTDIR"

# Matches the Makefile's previous fallback: a source tarball or a build outside
# a git checkout reports "unknown" rather than failing.
#
# HELIX_GIT_HASH overrides the git lookup entirely. This is how a cross build
# gets a real hash: the compile runs inside a container that bind-mounts only
# the source tree, and a git WORKTREE's .git is a *file* pointing at
# $MAIN/.git/worktrees/<name> — a path outside the mount. git therefore fails
# in the container and every worktree cross build silently stamped "unknown",
# leaving on-device evidence unattributable. mk/cross.mk resolves the hash on
# the host, where git always works, and passes it in with -e. Same escape hatch
# serves a packager building from an exported tarball with a known sha.
hash="unknown"
if [ -n "${HELIX_GIT_HASH:-}" ]; then
    hash="$HELIX_GIT_HASH"
elif command -v git >/dev/null 2>&1 && git -c safe.directory='*' rev-parse --git-dir >/dev/null 2>&1; then
    hash="$(git -c safe.directory='*' rev-parse --short HEAD 2>/dev/null || echo unknown)"
fi

{
    echo "// SPDX-License-Identifier: GPL-3.0-or-later"
    echo "// Auto-generated by gen-git-hash.sh - do not edit"
    echo "#pragma once"
    echo ""
    echo "#define HELIX_GIT_HASH \"$hash\""
} > "$TMPFILE"

# Only update if the content changed. Regenerating unconditionally would give
# the header a new mtime every build and rebuild helix_version.o for nothing.
if [ -f "$OUTFILE" ] && diff -q "$TMPFILE" "$OUTFILE" >/dev/null 2>&1; then
    exit 0
fi

cp "$TMPFILE" "$OUTFILE"
echo "Generated $OUTFILE ($hash)"
