#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Renders the installer's banner logo from the app icon into
# scripts/lib/installer/logo.sh: half-block text art for every terminal, plus
# kitty, iTerm2 and sixel images for terminals that can draw them. Needs
# python3 with Pillow.
# Usage: scripts/render-installer-logo.sh
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
src="$root/assets/images/helix-icon-256.png"
out="$root/scripts/lib/installer/logo.sh"

art() { python3 "$root/scripts/installer_logo_art.py" "$1" "$src"; }

{
    printf '#!/bin/sh\n# SPDX-License-Identifier: GPL-3.0-or-later\n'
    printf '# Generated by scripts/render-installer-logo.sh from assets/images/helix-icon-256.png.\n'
    printf '# Do not edit; re-run the script.\n\n'
    printf '_LOGO_PX="%s"\n\n' "$(art size)"
    printf '_logo_art() {\n    case "$1" in\n'
    for mode in 256 16 kitty iterm sixel; do
        case $mode in 256|16) kind=half$mode ;; *) kind=$mode ;; esac
        printf '        %s) cat <<'"'"'HELIX_LOGO_EOF'"'"'\n' "$mode"
        art "$kind"
        printf 'HELIX_LOGO_EOF\n            ;;\n'
    done
    printf '    esac\n}\n'
    cat <<'SH'

# Logotype colors match the wordmark: Helix in blue, Screen as a red to
# orange ramp. 16-color terminals get the nearest ANSI colors.
_logotype() {
    if [ "$UI_COLOR" = 256 ]; then
        printf '\033[1;38;5;33mHelix\033[38;5;197mSc\033[38;5;203mre\033[38;5;209me\033[38;5;214mn\033[0m'
    elif [ "$UI_COLOR" = 16 ]; then
        printf '\033[1;34mHelix\033[1;31mScr\033[1;33meen\033[0m'
    else
        printf 'HelixScreen'
    fi
}

# Ask the terminal what it can draw. One write carries a kitty graphics query,
# a cell-size request (CSI 16 t) and DA1. Every terminal answers DA1, and
# answers in order, so its reply ends the read with nothing left unread; the
# timeout only matters for a terminal that answers nothing at all.
_logo_probe() {
    _LOGO_REPLY=""
    _lp_tty="${HELIX_TTY_DEVICE:-/dev/tty}"
    _lp_old=$( (stty -g < "$_lp_tty") 2>/dev/null) || return 0
    stty -echo -icanon min 0 time 10 < "$_lp_tty" 2>/dev/null || return 0
    printf '\033_Gi=31,s=1,v=1,a=q,t=d,f=24;AAAA\033\\\033[16t\033[c' > "$_lp_tty"
    while _lp_in=$(dd bs=64 count=1 < "$_lp_tty" 2>/dev/null) && [ -n "$_lp_in" ]; do
        _LOGO_REPLY="$_LOGO_REPLY$_lp_in"
        case $_LOGO_REPLY in *"[?"*c) break ;; esac
    done
    stty "$_lp_old" < "$_lp_tty" 2>/dev/null
}

# Pick the logo from a probe reply: kitty, iterm, sixel or text. Also sets the
# cell size in pixels, guessing 9x18 when the terminal does not say.
# HELIX_INSTALL_LOGO=kitty|iterm|sixel|text forces the mode.
_logo_pick() { # reply
    _LOGO_CW=9; _LOGO_CH=18
    _lk_r=${1#*"[6;"}
    if [ "$_lk_r" != "$1" ]; then
        _lk_h=${_lk_r%%;*}; _lk_r=${_lk_r#*;}; _lk_w=${_lk_r%%t*}
        case "$_lk_h$_lk_w" in
            "" | *[!0-9]*) ;;
            *) [ "$_lk_h" -gt 0 ] && [ "$_lk_w" -gt 0 ] && { _LOGO_CW=$_lk_w; _LOGO_CH=$_lk_h; } ;;
        esac
    fi
    if [ -n "${HELIX_INSTALL_LOGO:-}" ]; then
        _LOGO_MODE=$HELIX_INSTALL_LOGO
        return 0
    fi
    _LOGO_MODE=text
    case $1 in
        *"_Gi=31;OK"*) _LOGO_MODE=kitty; return 0 ;;
    esac
    case "${LC_TERMINAL:-}:${TERM_PROGRAM:-}" in
        iTerm2:* | *:iTerm.app) _LOGO_MODE=iterm; return 0 ;;
    esac
    case $1 in
        *"[?"*c)
            _lk_da=${1##*"[?"}
            case ";${_lk_da%%c*};" in *";4;"*) _LOGO_MODE=sixel ;; esac
            ;;
    esac
}

# Draw an image with the logotype and subtitle to its right. Rows are
# reserved first so the image cannot scroll the screen out from under the
# saved cursor position the text is placed from.
_logo_image() { # mode subtitle
    _li_w=${_LOGO_PX% *}; _li_h=${_LOGO_PX#* }
    if [ "$1" = sixel ]; then
        _li_rows=$(( (_li_h + _LOGO_CH - 1) / _LOGO_CH ))
        _li_cols=$(( (_li_w + _LOGO_CW - 1) / _LOGO_CW ))
    else
        _li_rows=10
        _li_cols=$(( (_li_rows * _LOGO_CH * _li_w / _li_h + _LOGO_CW - 1) / _LOGO_CW ))
    fi
    _li_i=0
    while [ "$_li_i" -lt "$_li_rows" ]; do printf '\n'; _li_i=$((_li_i + 1)); done
    printf '\033[%sA\033%s  ' "$_li_rows" 7
    _logo_art "$1" | tr -d '\n'
    printf '\033%s' 8
    _li_mid=$(( (_li_rows + 1) / 2 ))
    _li_i=1
    while [ "$_li_i" -le "$_li_rows" ]; do
        if [ "$_li_i" = "$_li_mid" ]; then
            printf '\033[%sC%s' "$((_li_cols + 5))" "$(_logotype)"
        elif [ "$_li_i" = "$((_li_mid + 1))" ]; then
            printf '\033[%sC%s' "$((_li_cols + 5))" "$2"
        fi
        printf '\n'
        _li_i=$((_li_i + 1))
    done
}

print_banner() { # version channel
    if [ "$UI_TTY" != 1 ]; then
        printf 'HelixScreen installer %s (%s)\n' "$1" "$2" >&2
        return 0
    fi
    _pb_sub="$(printf '%b%s · %s channel%b' "$DIM" "$1" "$2" "$NC")"
    [ "$UI_UTF8" = 1 ] || _pb_sub="$(printf '%b%s (%s channel)%b' "$DIM" "$1" "$2" "$NC")"
    printf '\n' >&2
    _LOGO_MODE=text
    if [ "$UI_COLOR" != 0 ]; then
        # Graphics go to stderr, so only a terminal there is worth asking.
        _LOGO_REPLY=""
        [ -n "${HELIX_INSTALL_LOGO:-}" ] || { [ -t 2 ] && _logo_probe; }
        _logo_pick "$_LOGO_REPLY"
    fi
    case $_LOGO_MODE in
        kitty | iterm | sixel)
            _logo_image "$_LOGO_MODE" "$_pb_sub" >&2
            ;;
        *)
            if [ "$UI_UTF8" = 1 ] && [ "$UI_COLOR" != 0 ]; then
                _pb_i=0
                _logo_art "$UI_COLOR" | while IFS= read -r _pb_line; do
                    _pb_i=$((_pb_i + 1))
                    case $_pb_i in
                        6) printf '  %s\033[0m   %s\n' "$_pb_line" "$(_logotype)" ;;
                        7) printf '  %s\033[0m   %s\n' "$_pb_line" "$_pb_sub" ;;
                        *) printf '  %s\033[0m\n' "$_pb_line" ;;
                    esac
                done >&2
            else
                printf '  %s\n  %s\n' "$(_logotype)" "$_pb_sub" >&2
            fi
            ;;
    esac
    printf '\n' >&2
}
SH
} > "$out"
echo "wrote $out"
