// Copyright (C) 2025-2026 356C LLC
// SPDX-License-Identifier: GPL-3.0-or-later

#include "gcode_layer_index.h"
#include "gcode_streaming_controller.h"

#include <chrono>
#include <cstdio>
#include <fstream>
#include <future>
#include <string>
#include <thread>
#include <unistd.h>

#include "../catch_amalgamated.hpp"

using namespace helix::gcode;

namespace {

// Helper to create a temporary G-code file with test content
class TempGCodeFile {
  public:
    explicit TempGCodeFile(const std::string& content) {
        // Create temp file
        char temp_path[] = "/tmp/gcode_test_XXXXXX";
        int fd = mkstemp(temp_path);
        if (fd == -1) {
            throw std::runtime_error("Failed to create temp file");
        }
        close(fd);
        path_ = temp_path;

        // Write content
        std::ofstream out(path_);
        out << content;
        out.close();
    }

    ~TempGCodeFile() {
        std::remove(path_.c_str());
    }

    const std::string& path() const {
        return path_;
    }

  private:
    std::string path_;
};

// Simple multi-layer G-code for testing
const std::string SIMPLE_3_LAYER_GCODE = R"(
; Generated for testing
G28 ; Home all axes
G1 Z0.3 F1000 ; Move to first layer height
G1 X10 Y10 E1 F1500 ; Extrusion move layer 0
G1 X20 Y10 E2
G1 X20 Y20 E3
G1 X10 Y20 E4

G1 Z0.5 F1000 ; Layer 1
G1 X10 Y10 E5 ; Extrusion move layer 1
G1 X20 Y10 E6
G1 X20 Y20 E7

G1 Z0.7 F1000 ; Layer 2
G1 X15 Y15 E8 ; Extrusion move layer 2
G1 X25 Y15 E9
)";

// More complex G-code with metadata
const std::string GCODE_WITH_METADATA = R"(
; generated by PrusaSlicer 2.6.0
; filament_type = PLA
; estimated printing time = 15m 30s
G28
G1 Z0.2 F1000
G1 X50 Y50 E1 F1500
G1 X100 Y50 E2

G1 Z0.4
G1 X50 Y100 E3
G1 X100 Y100 E4
)";

// Build a file with `layers` layers of `moves_per_layer` extrusion moves each.
// Cache behaviour is only observable once the cached layer data is large
// relative to the cache budget: at 40 bytes per ToolpathSegment the fixtures
// above amount to a few hundred bytes, three orders of magnitude below the 1MB
// minimum budget, so nothing is ever evicted.
std::string make_dense_gcode(int layers, int moves_per_layer) {
    std::string gcode = "; dense test file\nG28\n";
    for (int layer = 0; layer < layers; ++layer) {
        gcode += "G1 Z" + std::to_string(0.2 * (layer + 1)) + " F1000\n";
        for (int i = 0; i < moves_per_layer; ++i) {
            gcode += "G1 X" + std::to_string(10 + i % 100) + " Y" +
                     std::to_string(10 + (i / 100) % 100) + " E" + std::to_string(i + 1) + "\n";
        }
    }
    return gcode;
}

} // namespace

TEST_CASE("GCodeStreamingController basic operations", "[gcode][streaming]") {
    TempGCodeFile temp_file(SIMPLE_3_LAYER_GCODE);

    SECTION("opens and closes files correctly") {
        GCodeStreamingController controller;

        REQUIRE_FALSE(controller.is_open());
        REQUIRE(controller.get_layer_count() == 0);

        REQUIRE(controller.open_file(temp_file.path()));
        REQUIRE(controller.is_open());
        REQUIRE(controller.get_layer_count() == 3);

        controller.close();
        REQUIRE_FALSE(controller.is_open());
        REQUIRE(controller.get_layer_count() == 0);
    }

    SECTION("reports correct source name") {
        GCodeStreamingController controller;
        controller.open_file(temp_file.path());

        REQUIRE(controller.get_source_name() == temp_file.path());
    }

    SECTION("returns nullptr for invalid file") {
        GCodeStreamingController controller;
        REQUIRE_FALSE(controller.open_file("/nonexistent/path/file.gcode"));
        REQUIRE_FALSE(controller.is_open());
    }
}

TEST_CASE("GCodeStreamingController layer access", "[gcode][streaming]") {
    TempGCodeFile temp_file(SIMPLE_3_LAYER_GCODE);
    GCodeStreamingController controller;
    REQUIRE(controller.open_file(temp_file.path()));

    SECTION("get_layer_segments returns data") {
        auto segments = controller.get_layer_segments(0);
        REQUIRE(segments != nullptr);
        REQUIRE(segments->size() > 0);

        // Verify it's extrusion data
        bool has_extrusion = false;
        for (const auto& seg : *segments) {
            if (seg.is_extrusion) {
                has_extrusion = true;
                break;
            }
        }
        REQUIRE(has_extrusion);
    }

    SECTION("get_layer_segments caches data") {
        // First access
        controller.get_layer_segments(1);
        REQUIRE(controller.is_layer_cached(1));

        // Second access should be cached
        auto segments = controller.get_layer_segments(1);
        REQUIRE(segments != nullptr);
    }

    SECTION("returns nullptr for out of range layer") {
        auto segments = controller.get_layer_segments(999);
        REQUIRE(segments == nullptr);
    }

    SECTION("get_layer_z returns correct heights") {
        float z0 = controller.get_layer_z(0);
        float z1 = controller.get_layer_z(1);
        float z2 = controller.get_layer_z(2);

        // Layers should be at increasing Z heights
        REQUIRE(z0 < z1);
        REQUIRE(z1 < z2);

        // Check approximate values from test G-code
        REQUIRE(z0 == Catch::Approx(0.3f).epsilon(0.1));
        REQUIRE(z1 == Catch::Approx(0.5f).epsilon(0.1));
        REQUIRE(z2 == Catch::Approx(0.7f).epsilon(0.1));
    }

    SECTION("find_layer_at_z works") {
        REQUIRE(controller.find_layer_at_z(0.3f) == 0);
        REQUIRE(controller.find_layer_at_z(0.5f) == 1);
        REQUIRE(controller.find_layer_at_z(0.7f) == 2);

        // Approximate matches
        REQUIRE(controller.find_layer_at_z(0.35f) == 0);
        REQUIRE(controller.find_layer_at_z(0.45f) == 1);
    }
}

TEST_CASE("GCodeStreamingController cache management", "[gcode][streaming]") {
    TempGCodeFile temp_file(SIMPLE_3_LAYER_GCODE);

    SECTION("cache budget can be set") {
        GCodeStreamingController controller(4 * 1024 * 1024); // 4MB
        controller.open_file(temp_file.path());

        REQUIRE(controller.get_cache_budget() == 4 * 1024 * 1024);

        controller.set_cache_budget(8 * 1024 * 1024);
        REQUIRE(controller.get_cache_budget() == 8 * 1024 * 1024);
    }

    SECTION("minimum budget is enforced") {
        GCodeStreamingController controller;
        controller.set_cache_budget(100); // Too small

        REQUIRE(controller.get_cache_budget() >= GCodeStreamingController::MIN_CACHE_BUDGET);
    }

    SECTION("clear_cache works") {
        GCodeStreamingController controller;
        controller.open_file(temp_file.path());

        controller.get_layer_segments(0);
        controller.get_layer_segments(1);
        REQUIRE(controller.get_cache_memory_usage() > 0);

        // get_layer_segments() schedules a prefetch of the neighbouring layers on
        // the worker thread, and clear_cache() does not quiesce it. Without this
        // sync the worker's next cache_.get_or_load() can land between the clear
        // and the assert below, leaving usage non-zero. Same reason the prefetch
        // sections further down sync before asserting.
        controller.wait_for_prefetch_idle();

        controller.clear_cache();
        REQUIRE(controller.get_cache_memory_usage() == 0);
    }

    SECTION("cache hit rate is tracked") {
        GCodeStreamingController controller;
        REQUIRE(controller.open_file(temp_file.path()));

        // The prefetch worker's loads go through the same cache_.get_or_load()
        // as a caller's, so they land in the same hit and miss counters. Only
        // load_layer_segments_no_prefetch() leaves the worker unstarted, which
        // is what makes the count below the caller's alone.
        REQUIRE(controller.load_layer_segments_no_prefetch(0) != nullptr);
        REQUIRE(controller.load_layer_segments_no_prefetch(0) != nullptr);
        REQUIRE(controller.load_layer_segments_no_prefetch(0) != nullptr);

        // One load of layer 0 followed by two reads of the resident copy.
        REQUIRE(controller.get_cache_hit_rate() == Catch::Approx(2.0f / 3.0f));
    }

    SECTION("prefetch loads count toward the hit rate") {
        GCodeStreamingController controller;
        REQUIRE(controller.open_file(temp_file.path()));

        // A prefetch run from centre 0 reaches every layer of this file, so each
        // run touches all of them exactly once.
        const size_t layer_count = controller.get_layer_count();
        REQUIRE(layer_count == 3);
        REQUIRE(GCodeStreamingController::DEFAULT_PREFETCH_RADIUS + 1 >= layer_count);

        // Syncing after each call pins how many runs happen: the worker takes
        // one centre at a time and drops a queued centre in favour of a newer
        // one, so back-to-back calls would coalesce into an unknown number.
        controller.get_layer_segments(0);    // miss 0
        controller.wait_for_prefetch_idle(); // hit 0, miss 1, miss 2
        controller.get_layer_segments(0);    // hit 0
        controller.wait_for_prefetch_idle(); // hit 0, hit 1, hit 2

        // 5 hits against 3 misses.
        REQUIRE(controller.get_cache_hit_rate() == Catch::Approx(5.0f / 8.0f));
    }
}

TEST_CASE("GCodeStreamingController prefetch", "[gcode][streaming]") {
    // Create a larger file with more layers
    std::string large_gcode = "; Test file\nG28\n";
    for (int layer = 0; layer < 20; ++layer) {
        float z = 0.2f + layer * 0.2f;
        large_gcode += "G1 Z" + std::to_string(z) + " F1000\n";
        large_gcode +=
            "G1 X" + std::to_string(10 + layer) + " Y10 E" + std::to_string(layer + 1) + " F1500\n";
    }

    TempGCodeFile temp_file(large_gcode);
    GCodeStreamingController controller;
    REQUIRE(controller.open_file(temp_file.path()));

    // Prefetch runs on a worker thread — it used to run inline, which is exactly
    // what put up to 2*radius+1 seek-and-parses on the LVGL main thread. The
    // requested layer is still loaded synchronously; only the NEIGHBOURS are
    // asynchronous, so these sections sync on wait_for_prefetch_idle() before
    // asserting on them.

    SECTION("prefetch loads nearby layers") {
        // Clear any auto-prefetched layers
        controller.clear_cache();

        // Access layer 10, which should prefetch layers 7-13
        controller.get_layer_segments(10);

        // The requested layer is loaded before the call returns.
        REQUIRE(controller.is_layer_cached(10));

        controller.wait_for_prefetch_idle();

        // Nearby layers should be cached
        REQUIRE(controller.is_layer_cached(9));
        REQUIRE(controller.is_layer_cached(11));

        // Distant layers should not be cached
        REQUIRE_FALSE(controller.is_layer_cached(0));
        REQUIRE_FALSE(controller.is_layer_cached(19));
    }

    SECTION("explicit prefetch works") {
        controller.clear_cache();
        controller.prefetch_around(5, 2);
        controller.wait_for_prefetch_idle();

        // Layers 3-7 should be cached
        for (size_t i = 3; i <= 7; ++i) {
            REQUIRE(controller.is_layer_cached(i));
        }
    }
}

TEST_CASE("GCodeStreamingController index stats", "[gcode][streaming]") {
    TempGCodeFile temp_file(SIMPLE_3_LAYER_GCODE);
    GCodeStreamingController controller;

    SECTION("stats available after open") {
        REQUIRE(controller.open_file(temp_file.path()));

        const auto& stats = controller.get_index_stats();
        REQUIRE(stats.total_layers == 3);
        REQUIRE(stats.total_lines > 0);
        REQUIRE(stats.total_bytes > 0);
        REQUIRE(stats.min_z > 0.0f);
        REQUIRE(stats.max_z > stats.min_z);
        REQUIRE(stats.extrusion_moves > 0);
    }

    SECTION("file size is reported") {
        controller.open_file(temp_file.path());
        REQUIRE(controller.get_file_size() > 0);
    }
}

TEST_CASE("GCodeStreamingController async operations", "[gcode][streaming]") {
    TempGCodeFile temp_file(SIMPLE_3_LAYER_GCODE);

    SECTION("async open completes") {
        GCodeStreamingController controller;
        std::atomic<bool> completed{false};
        std::atomic<bool> success{false};

        controller.open_file_async(temp_file.path(), [&](bool result) {
            success.store(result);
            completed.store(true);
        });

        // Wait for completion (with timeout)
        auto start = std::chrono::steady_clock::now();
        while (!completed.load()) {
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
            auto elapsed = std::chrono::steady_clock::now() - start;
            if (elapsed > std::chrono::seconds(5)) {
                FAIL("Async open timed out");
                break;
            }
        }

        REQUIRE(success.load());
        REQUIRE(controller.is_open());
        REQUIRE(controller.get_layer_count() == 3);
    }

    SECTION("is_indexing returns correct state") {
        GCodeStreamingController controller;

        REQUIRE_FALSE(controller.is_indexing());

        // Start async open
        controller.open_file_async(temp_file.path());

        // May or may not still be indexing depending on timing
        // Just verify it doesn't crash
        bool was_indexing = controller.is_indexing();
        (void)was_indexing;

        // Wait for completion
        while (controller.is_indexing()) {
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
        }

        REQUIRE_FALSE(controller.is_indexing());
    }
}

TEST_CASE("GCodeStreamingController memory pressure", "[gcode][streaming]") {
    TempGCodeFile temp_file(SIMPLE_3_LAYER_GCODE);
    GCodeStreamingController controller;
    controller.open_file(temp_file.path());

    SECTION("respond_to_memory_pressure evicts down to the emergency budget") {
        // The explicit-budget constructor leaves adaptive mode off, so the
        // emergency budget is exactly half the cache budget rather than being
        // floored at adaptive_min_budget. Three dense layers overshoot that
        // half, which is what makes the eviction observable.
        TempGCodeFile dense_file(make_dense_gcode(3, 6000));
        GCodeStreamingController dense(GCodeStreamingController::MIN_CACHE_BUDGET);
        REQUIRE(dense.open_file(dense_file.path()));
        REQUIRE(dense.get_layer_count() == 3);

        // no_prefetch keeps the background warmer out of the cache, so what is
        // resident is exactly what this section loaded.
        for (size_t i = 0; i < 3; ++i) {
            REQUIRE(dense.load_layer_segments_no_prefetch(i) != nullptr);
        }

        const size_t emergency_budget = dense.get_cache_budget() / 2;
        const size_t before = dense.get_cache_memory_usage();
        REQUIRE(before > emergency_budget);

        dense.respond_to_memory_pressure();

        const size_t after = dense.get_cache_memory_usage();
        CHECK(after < before);
        CHECK(after <= emergency_budget);
    }

    SECTION("adaptive cache keeps the cache usable and within budget") {
        controller.set_adaptive_cache(true);
        REQUIRE(controller.get_layer_segments(0) != nullptr);
        CHECK(controller.get_cache_memory_usage() > 0);
        CHECK(controller.get_cache_memory_usage() <= controller.get_cache_budget());
    }
}

TEST_CASE("GCodeStreamingController error handling", "[gcode][streaming]") {
    SECTION("handles close when not open") {
        GCodeStreamingController controller;
        controller.close(); // Should not crash
        REQUIRE_FALSE(controller.is_open());
    }

    SECTION("handles repeated open") {
        TempGCodeFile temp_file(SIMPLE_3_LAYER_GCODE);
        GCodeStreamingController controller;

        controller.open_file(temp_file.path());
        REQUIRE(controller.is_open());

        // Open again should close first and reopen
        controller.open_file(temp_file.path());
        REQUIRE(controller.is_open());
    }

    SECTION("empty stats when not open") {
        GCodeStreamingController controller;
        const auto& stats = controller.get_index_stats();

        REQUIRE(stats.total_layers == 0);
        REQUIRE(stats.total_bytes == 0);
    }
}

// =============================================================================
// BackgroundGhostBuilder Tests
// =============================================================================

TEST_CASE("BackgroundGhostBuilder basic operations", "[gcode][streaming][ghost]") {
    TempGCodeFile temp_file(SIMPLE_3_LAYER_GCODE);
    GCodeStreamingController controller;
    REQUIRE(controller.open_file(temp_file.path()));

    SECTION("initial state is correct") {
        BackgroundGhostBuilder builder;

        REQUIRE_FALSE(builder.is_running());
        REQUIRE_FALSE(builder.is_complete());
        REQUIRE(builder.get_progress() == 0.0f);
        REQUIRE(builder.layers_rendered() == 0);
    }

    SECTION("starts and completes with callback") {
        BackgroundGhostBuilder builder;
        std::atomic<size_t> layers_rendered{0};
        std::atomic<size_t> segments_received{0};

        builder.start(&controller, [&](size_t layer_idx, const std::vector<ToolpathSegment>& segs) {
            layers_rendered++;
            segments_received += segs.size();
        });

        // Wait for completion
        auto start = std::chrono::steady_clock::now();
        while (!builder.is_complete()) {
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
            auto elapsed = std::chrono::steady_clock::now() - start;
            if (elapsed > std::chrono::seconds(5)) {
                FAIL("Ghost builder timed out");
                break;
            }
        }

        REQUIRE(builder.is_complete());
        REQUIRE_FALSE(builder.is_running());
        REQUIRE(builder.get_progress() == 1.0f);
        REQUIRE(builder.layers_rendered() == 3);
        REQUIRE(layers_rendered.load() == 3);
        REQUIRE(segments_received.load() > 0);
    }

    SECTION("reports progress during build") {
        // Create a larger file for more measurable progress
        std::string large_gcode = "; Test file\nG28\n";
        for (int layer = 0; layer < 50; ++layer) {
            float z = 0.2f + layer * 0.2f;
            large_gcode += "G1 Z" + std::to_string(z) + " F1000\n";
            large_gcode += "G1 X" + std::to_string(10 + layer) + " Y10 E" +
                           std::to_string(layer + 1) + " F1500\n";
        }
        TempGCodeFile large_file(large_gcode);

        GCodeStreamingController large_controller;
        REQUIRE(large_controller.open_file(large_file.path()));

        BackgroundGhostBuilder builder;
        std::vector<float> progress_samples;
        std::mutex samples_mutex;

        builder.start(&large_controller,
                      [&](size_t /*layer_idx*/, const std::vector<ToolpathSegment>& /*segs*/) {
                          // Record progress at each layer
                          float p = builder.get_progress();
                          std::lock_guard<std::mutex> lock(samples_mutex);
                          progress_samples.push_back(p);
                      });

        // Wait for completion
        auto start = std::chrono::steady_clock::now();
        while (!builder.is_complete()) {
            std::this_thread::sleep_for(std::chrono::milliseconds(5));
            auto elapsed = std::chrono::steady_clock::now() - start;
            if (elapsed > std::chrono::seconds(10)) {
                FAIL("Ghost builder timed out");
                break;
            }
        }

        REQUIRE(builder.is_complete());
        REQUIRE(builder.total_layers() == 50);

        // Verify progress increased monotonically
        std::lock_guard<std::mutex> lock(samples_mutex);
        REQUIRE(progress_samples.size() > 0);
        for (size_t i = 1; i < progress_samples.size(); ++i) {
            REQUIRE(progress_samples[i] >= progress_samples[i - 1]);
        }
    }
}

TEST_CASE("BackgroundGhostBuilder cancellation", "[gcode][streaming][ghost]") {
    // Create larger file so we have time to cancel
    std::string large_gcode = "; Test file\nG28\n";
    for (int layer = 0; layer < 100; ++layer) {
        float z = 0.2f + layer * 0.2f;
        large_gcode += "G1 Z" + std::to_string(z) + " F1000\n";
        for (int seg = 0; seg < 10; ++seg) {
            large_gcode += "G1 X" + std::to_string(10 + seg) + " Y" + std::to_string(10 + seg) +
                           " E" + std::to_string(layer * 10 + seg + 1) + " F1500\n";
        }
    }
    TempGCodeFile temp_file(large_gcode);

    GCodeStreamingController controller;
    REQUIRE(controller.open_file(temp_file.path()));

    SECTION("cancel stops the build") {
        BackgroundGhostBuilder builder;
        std::atomic<size_t> layers_rendered{0};

        builder.start(&controller, [&](size_t /*layer_idx*/, const std::vector<ToolpathSegment>&) {
            layers_rendered++;
            // Add a small delay to make cancellation easier
            std::this_thread::sleep_for(std::chrono::milliseconds(5));
        });

        // Let it run briefly
        std::this_thread::sleep_for(std::chrono::milliseconds(50));

        // Cancel
        builder.cancel();

        // Should have stopped before completing all layers
        REQUIRE_FALSE(builder.is_running());
        REQUIRE_FALSE(builder.is_complete()); // Was cancelled, not completed
        REQUIRE(layers_rendered.load() < 100);
    }

    SECTION("cancel is idempotent") {
        BackgroundGhostBuilder builder;

        // Cancel without starting - should be safe
        builder.cancel();
        builder.cancel();
        REQUIRE_FALSE(builder.is_running());
    }

    SECTION("destructor cancels automatically") {
        // Each layer costs LAYER_COST_MS in the render callback, so a destructor
        // that only joins (never signals cancel) has to drain every remaining
        // layer. One that cancels first waits out at most the layer in flight.
        constexpr int LAYER_COST_MS = 400;

        std::atomic<bool> callback_called{false};
        std::atomic<size_t> layers_seen{0};
        size_t total_layers = 0;
        auto teardown_start = std::chrono::steady_clock::now();

        {
            BackgroundGhostBuilder builder;
            builder.start(&controller, [&](size_t, const std::vector<ToolpathSegment>&) {
                callback_called = true;
                layers_seen++;
                std::this_thread::sleep_for(std::chrono::milliseconds(LAYER_COST_MS));
            });

            total_layers = builder.total_layers();

            // Wait for the worker to actually enter the render callback. Polling
            // beats a fixed sleep: it neither races a slow thread start nor
            // burns time on a fast one.
            auto deadline = std::chrono::steady_clock::now() + std::chrono::seconds(5);
            while (!callback_called.load() && std::chrono::steady_clock::now() < deadline) {
                std::this_thread::sleep_for(std::chrono::milliseconds(1));
            }

            teardown_start = std::chrono::steady_clock::now();
            // Destructor should cancel and join
        }
        auto teardown_ms = std::chrono::duration_cast<std::chrono::milliseconds>(
                               std::chrono::steady_clock::now() - teardown_start)
                               .count();

        // The worker reached the render callback at all - without this the two
        // checks below would pass against a builder that never started a thread.
        REQUIRE(callback_called);
        REQUIRE(total_layers >= 2);

        // A cancel-then-join waits out only the layer in flight (~400ms). A
        // join-without-cancel waits out every remaining layer, and the fixture
        // has ~100 of them, so it runs tens of seconds. The threshold sits at 2x
        // the expected value - enough headroom that CI load will not trip it,
        // and nowhere near a full drain.
        INFO("teardown took " << teardown_ms << "ms");
        REQUIRE(teardown_ms < LAYER_COST_MS * 2);

        // Same property from the other side, and immune to how loaded the
        // machine is: the destructor tore down mid-build, so the remaining
        // layers were never rendered at all.
        INFO("rendered " << layers_seen.load() << " of " << total_layers << " layers");
        REQUIRE(layers_seen.load() < total_layers);
    }
}

TEST_CASE("BackgroundGhostBuilder UI yielding", "[gcode][streaming][ghost]") {
    TempGCodeFile temp_file(SIMPLE_3_LAYER_GCODE);
    GCodeStreamingController controller;
    REQUIRE(controller.open_file(temp_file.path()));

    SECTION("notify_user_request can be called during build") {
        BackgroundGhostBuilder builder;

        builder.start(&controller, [&](size_t, const std::vector<ToolpathSegment>&) {
            // Simulate user navigation during build
            builder.notify_user_request();
        });

        // Wait for completion
        auto start = std::chrono::steady_clock::now();
        while (!builder.is_complete()) {
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
            auto elapsed = std::chrono::steady_clock::now() - start;
            if (elapsed > std::chrono::seconds(5)) {
                FAIL("Ghost builder timed out");
                break;
            }
        }

        REQUIRE(builder.is_complete());
    }
}

TEST_CASE("BackgroundGhostBuilder error handling", "[gcode][streaming][ghost]") {
    SECTION("start with closed controller does nothing") {
        GCodeStreamingController controller;
        BackgroundGhostBuilder builder;

        // Controller is not open
        builder.start(&controller, [](size_t, const std::vector<ToolpathSegment>&) {});

        // Should not start
        REQUIRE_FALSE(builder.is_running());
        REQUIRE_FALSE(builder.is_complete());
    }

    SECTION("start with null controller does nothing") {
        BackgroundGhostBuilder builder;

        builder.start(nullptr, [](size_t, const std::vector<ToolpathSegment>&) {});

        REQUIRE_FALSE(builder.is_running());
    }

    SECTION("restart cancels previous build") {
        TempGCodeFile temp_file(SIMPLE_3_LAYER_GCODE);
        GCodeStreamingController controller;
        REQUIRE(controller.open_file(temp_file.path()));

        BackgroundGhostBuilder builder;
        std::atomic<int> callback_count{0};

        // Start first build
        builder.start(&controller, [&](size_t, const std::vector<ToolpathSegment>&) {
            callback_count++;
            std::this_thread::sleep_for(std::chrono::milliseconds(50));
        });

        // Start second build immediately (should cancel first)
        builder.start(&controller,
                      [&](size_t, const std::vector<ToolpathSegment>&) { callback_count++; });

        // Wait for second build to complete
        auto start = std::chrono::steady_clock::now();
        while (!builder.is_complete()) {
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
            auto elapsed = std::chrono::steady_clock::now() - start;
            if (elapsed > std::chrono::seconds(5)) {
                FAIL("Ghost builder timed out");
                break;
            }
        }

        REQUIRE(builder.is_complete());
        // Should have rendered all layers from second build
        REQUIRE(builder.layers_rendered() == 3);
    }
}

// =============================================================================
// Index cancellation
//
// close() and the destructor join an in-flight index build on the CALLING
// thread. On a Q2-class device indexing a large file runs for tens of
// seconds, so if the build cannot be stopped, backing out of a preview
// mid-index freezes the UI for the rest of the build (#1706). The progress
// callback is the stop signal: build_from_file polls it and unwinds.
// =============================================================================

namespace {

// A file big enough that indexing it takes a measurable fraction of a second.
// Indexing throughput is ~300 MB/s on current dev hardware, so ~100 MB buys a
// ~300 ms full build: long enough that a cancelled build finishing at full
// speed is clearly distinguishable, short enough to keep the suite quick.
class BigGCodeFile {
  public:
    explicit BigGCodeFile(uint64_t target_bytes) {
        char temp_path[] = "/tmp/gcode_cancel_test_XXXXXX";
        int fd = mkstemp(temp_path);
        if (fd == -1) {
            throw std::runtime_error("Failed to create temp file");
        }
        path_ = temp_path;

        // One block per layer: a marker, the Z move that starts the layer
        // (marker mode waits for it), then plain moves, ~0.5 MB. The line
        // count is what indexes the file; content only has to parse.
        std::string block = ";LAYER:block\nG1 Z0.400 F600\n";
        while (block.size() < 500 * 1024) {
            block += "G1 X100.000 Y100.000 E1.0000\n";
        }

        FILE* f = fdopen(fd, "w");
        if (!f) {
            close(fd);
            throw std::runtime_error("Failed to open temp file for writing");
        }
        uint64_t written = 0;
        while (written < target_bytes) {
            if (fwrite(block.data(), 1, block.size(), f) == 0) {
                fclose(f);
                throw std::runtime_error("Failed to write temp file");
            }
            written += block.size();
        }
        fclose(f);
    }

    ~BigGCodeFile() {
        std::remove(path_.c_str());
    }

    const std::string& path() const {
        return path_;
    }

  private:
    std::string path_;
};

using SteadyClock = std::chrono::steady_clock;

template <typename F> SteadyClock::duration timed(F&& f) {
    const auto start = SteadyClock::now();
    f();
    return SteadyClock::now() - start;
}

long ms_of(SteadyClock::duration d) {
    return std::chrono::duration_cast<std::chrono::milliseconds>(d).count();
}

} // namespace

TEST_CASE("index build stops when the progress callback withdraws consent",
          "[gcode][streaming][cancel]") {
    BigGCodeFile file(100ull * 1024 * 1024);
    GCodeLayerIndex index;

    const auto full = timed([&] { REQUIRE(index.build_from_file(file.path())); });

    bool completed = true;
    const auto cancelled =
        timed([&] { completed = index.build_from_file(file.path(), [](float) { return false; }); });
    REQUIRE_FALSE(completed);
    REQUIRE(ms_of(cancelled) * 2 < ms_of(full));
}

TEST_CASE("close during async indexing returns promptly", "[gcode][streaming][cancel]") {
    BigGCodeFile file(200ull * 1024 * 1024);
    GCodeStreamingController controller;

    // Time one full synchronous build on THIS machine; the bound for a
    // mid-index close is derived from it so the test holds at any host speed.
    const auto full = timed([&] { REQUIRE(controller.open_file(file.path())); });
    controller.close();

    std::atomic<bool> completed{false};
    controller.open_file_async(file.path(), [&](bool) { completed.store(true); });

    while (!completed.load() && !controller.is_indexing()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(2));
    }
    // Land the close a few percent into the build: early enough that most of
    // the work is still ahead, late enough that it is genuinely running.
    while (!completed.load() && controller.get_index_progress() < 0.05f) {
        std::this_thread::sleep_for(std::chrono::milliseconds(2));
    }

    const auto close_time = timed([&] { controller.close(); });
    REQUIRE(ms_of(close_time) * 2 < ms_of(full));
}

TEST_CASE("close in the async launch window still cancels the build",
          "[gcode][streaming][cancel]") {
    // The window between open_file_async's std::async and the worker's first
    // instruction is real: a close() landing there arms
    // index_cancel_requested_ and blocks on the future, so if the worker
    // resets the flag as it starts, the caller asked to stop and the build
    // runs to completion anyway under it (#1706: backing out of a preview
    // must not freeze the UI for the rest of the build). The gate parks the
    // worker inside that window so the scheduling race is deterministic.
    BigGCodeFile file(200ull * 1024 * 1024);
    GCodeStreamingController controller;

    const auto full = timed([&] { REQUIRE(controller.open_file(file.path())); });
    controller.close();

    std::promise<void> parked_promise;
    auto parked = parked_promise.get_future();
    std::promise<void> release_promise;
    auto release = release_promise.get_future().share();

    // However the assertions below end, the gate must go back to null: a
    // parked gate would hang every later async open in this binary.
    struct GateGuard {
        ~GateGuard() {
            GCodeStreamingController::index_worker_gate = nullptr;
        }
    } gate_guard;
    GCodeStreamingController::index_worker_gate = [&] {
        parked_promise.set_value();
        release.wait_for(std::chrono::seconds(10));
    };

    std::atomic<bool> completed{false};
    std::atomic<bool> result{true};
    controller.open_file_async(file.path(), [&](bool ok) {
        result.store(ok);
        completed.store(true);
    });
    REQUIRE(parked.wait_for(std::chrono::seconds(10)) == std::future_status::ready);

    // The worker is parked before build_index: this close() lands in the
    // launch window and must not wait out a full build once it is let go.
    std::thread closer([&] { controller.close(); });
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    const auto released = SteadyClock::now();
    release_promise.set_value();
    closer.join();
    const long wait_ms = ms_of(SteadyClock::now() - released);

    REQUIRE(completed.load());
    REQUIRE_FALSE(result.load());
    REQUIRE(wait_ms * 3 < ms_of(full));
}
